### ISSUE TITLE
Bug - Small Bales Loaded/Unloaded with mod not accepted by Vanilla Autoloader

### ISSUE THREAD

**Issue by screaney** [loki79uk/FS22_UniversalAutoload#6] opened 2022-02-23 15:28 UTC
If I use a trailer with this mod to load/unload small square bales, then attempt to load them with the vanilla autoloader, that autoloader gives message that I cannot mix bales.  It appears to modify the bales somehow to the vanilla autoloader does not accept them.

**Comment by loki79uk** [comment] 2022-02-23 15:33
Understood.  I can't look at this until the weekend, but I can have a look at the other autoloader code before then to see what the problem could be.  All I do with bales is remove and add again to physics, so I'm not sure what could be going on there.  Thanks for letting me know.

**Comment by tonto1992** [comment] 2022-02-24 03:39
Something that happened to me tonight might be related: 
(tl;dr version: modded bale wrapper not accepting bales from the modded baler/windrower after being loaded/unloaded in a vanilla Krone Profi liner with your mod). Details below 

long version: I was mowing and using a modded baler (baler/windrow combo (FS22_Claas_Krone_Baler_Pack_With_Lizard_R90)).  Bale size is 240cm (I hadn't tried any other sizes so I don't have any data about those).  I could successfully load and unload these bales with your mod (using a vanilla Krone Profi liner, so that's no problem).  BUT when the modded bale wrapper (FS22_KuhnSW4014) tries to put them up, it says "this bale is not supported" and fails to get it.   The bales that were not picked up, however, by the vanilla trailer were able to be processed normally by the wrapper.
 
 So I don't know if these are related to the parent post or not.  I can create a separate issue if you'd like.

**Comment by loki79uk** [comment] 2022-02-24 07:07
Sounds related, thanks for letting me know.  No need to create a second issue.  I can always do that if I find they are not related.  Thanks again!

**Comment by loki79uk** [comment] 2022-02-26 15:27
I was planning to have looked at this already, but have been distracted by the MP problems introduced with 1.3.  I will set up a savegame to test this and update here when I find anything.

**Comment by loki79uk** [comment] 2022-03-02 19:19
I have reproduced the original bug.  I also found out that a game save and reload resets the small bales so that they load into the autostacker again.  I'll try to figure out exactly what property of the bales is changing after autoloading!

**Comment by loki79uk** [comment] 2022-03-03 01:17
This should be fixed now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-011

**Comment by loki79uk** [comment] 2022-03-03 09:02
> Something that happened to me tonight might be related: (tl;dr version: modded bale wrapper not accepting bales from the modded baler/windrower after being loaded/unloaded in a vanilla Krone Profi liner with your mod). Details below

I have not reproduced this one to confim, but from the cause (that is now corrected), I'm pretty sure that this was 100% related and should be fixed now.

**Closed** 2022-03-05 12:36 UTC
