### ISSUE TITLE
Add support for the Gyrax P22700 Straw Blower (or a base game straw blower)

### ISSUE THREAD

**Issue by ggoosen** [loki79uk/FS22_UniversalAutoload#233] opened 2024-06-15 13:11 UTC
If possible, could you add support for in game straw blowers or this mod? 

I tried adding this myself to the mod, and it works to an extent, but i have some issues. 

I defined the "cube" in giants as large as the open doors, that helps the mod calculate the placement of the 
1) The trailer is super heavy after loading
2) As soon as i start "unloading" or cutting up the straw the bales disapear (even though they still in there)

https://www.farming-simulator.com/mod.php?mod_id=283397&title=fs2022

![Farming Simulator 22 15_06_2024 10_36_01 PM](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/17799551-ecdb-4cb1-8691-05fb78e882b5)

![Screenshot 2024-06-15 223750](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/71d48981-00dd-4864-a940-59192ee8979a)

**Comment by loki79uk** [comment] 2024-06-15 14:49
Hi, that is an idea I had never even thought of.  It would need some modifications to standard autoload, since you would load the bales and then not expect to unload them.  It could work in a similar way for a TMR wagon too.  It might be more of a feature to add to the next version of UAL, which I'm thinking of starting soon with all the talk about FS25!

**Comment by ggoosen** [comment] 2024-06-15 14:52
Thanks @loki79uk, it works currently (supprisingly) other than the fact that the bales disapear visually. I thought i might be easy with a quick tweek. But ill leave it to you to decide :)

**Comment by loki79uk** [comment] 2024-06-15 16:17
Try with the latest release now.  There is no actual support for straw blowers, but it should work now without the errors caused by dissapearing bales.  I noticed the first issue that needs solving is that the loading triggers need to be lower.  i.e. Putting the loading zone too high up means you cannot detect bales on the ground.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.5.1.5

**Comment by ggoosen** [comment] 2024-06-16 00:22
Tested it now, that works.  Just need to make sure you bind the horizontal loading so that it doesnt stack. 

Uploading the updated version of the MOD incase anyone wants to try it. 

[FS22_Gyrax_P22700_UAL.zip](https://github.com/user-attachments/files/15855676/FS22_Gyrax_P22700_UAL.zip)

Note this is not my work, this is Black Sheep Moddings work, credit goes to them 
https://www.farming-simulator.com/mod.php?mod_id=283397&title=fs2022

**Comment by ggoosen** [comment] 2024-06-17 02:28
Will look into adding it to mod settings, i assume that would work for the standard items as well? Like the little John Deer trailer which doesnt have standard support? 

Below is what it looks like for me when i load and have it as "double" Ideally i would want a small gap between left and right bales, but it still works like this when you close the trailer.

![Farming Simulator 22 17_06_2024 11_55_25 AM](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/6774087b-c51b-4a9f-aaa8-0a645d95f6c4)

**Comment by ggoosen** [comment] 2024-06-17 06:57
I tried to add the following and received an error that it cannot load the XML 

<vehicleConfiguration configFileName="FS22_StrawBlower_Gyrax_P22700/Gyrax_P22700.xml>
		<loadingArea offset="0.000 1.000 -1.241" width="5.5" height="5.25" length="5.2"/>
		<options noLoadingIfFolded="true" isBaleTrailer="true" enableSideLoading="true" showDebug="false"/>
</vehicleConfiguration>


I did however manage to add the little trailer, using the below. What does the "selectedConfigs" do? 

<vehicleConfiguration configFileName="data/vehicles/salek/ans1900/ans1900.xml" selectedConfigs="2">
		<loadingArea offset="0 1.000 -0.446" width="1.3" height="1.25" length="2.3"/>
		<options enableRearLoading="true" enableSideLoading="true" showDebug="true"/>
</vehicleConfiguration>

Also the "placement" zone is slightly higher than it should be? is that calculated?

![Farming Simulator 22 17_06_2024 4_25_03 PM](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/bf03be14-1565-43fe-a1ee-29f99c45e1f1)

**Comment by loki79uk** [comment] 2024-06-17 08:16
I'm at work so can't check until later, but where did you get those numbers from for the Salek?  I assume it would be the same as the other one that is added.
```xml
        <vehicleConfiguration configFileName="data/vehicles/salek/ans1900/ans1900.xml" selectedConfigs="1">
            <loadingArea offset="0 0.589 -0.48" width="1.50" height="1.85" length="2.45"/>
        </vehicleConfiguration>
```
The selected configs is the configuration that you have selected in the shop, e.g. bale trailer, bulk fill, etc.  There are issues with loading pallets into the bulk fill trailers since they immediately unload (convert to loose fill types), so I typically don't add UAL to those trailers.

**Comment by ggoosen** [comment] 2024-06-17 08:28
For the Salek, i opened the i3d file in giants editor and placed a cube onto the trailer to use the reference numbers. 

If i change the 1 to 0.589 will bring the cube down? closer to the tray?

Understood on the selected config now :)

**Comment by loki79uk** [comment] 2024-06-17 08:41
It sounds like you almost did it correctly, but before placing it you need to offset the y-coordinate of the cube by 0.5 and then "freeze transformations":

```
   · Create a unit cube and set "Translate Y" = 0.5
   · "Freeze Transformations" with default options (reference node should move to centre of lower face)
   · Use "Interactive Placement" to set the height
        - Ctrl+B with the box selected
        - Left-click on the bed of the trailer
        - Manually set both X and Z coordinates back to zero
   · Adjust Scale (X,Y,Z) and Translate Z (if required) to position and scale the loading area
   · Copy those values into the vehicle xml using the format:
    <loadingArea offset="offsetX offsetY offsetZ" width="scaleX" height="scaleY" length="scaleZ"/>
   · Delete the shape or close without saving (we ONLY need the values)
```

**Comment by loki79uk** [comment] 2024-06-19 08:49
Check the whole file in a proper xml editor like notepad++.  You have one opening comment tag `<!--`, but two closing tags `-->`

**Comment by ggoosen** [comment] 2024-06-19 08:50
I was to quick on the post, i noticed that and removed it and tested again, "comment close tags" was not the issue, same error.

**Comment by loki79uk** [comment] 2024-06-19 08:52
is this the full path of the xml inside the mod?
`FS22_HerculanoHF/HF.xml`

have you edited that file at all and possibly broken the xml there?

**Comment by loki79uk** [comment] 2024-06-19 09:00
Actually, it looks like it is not loading the file:
https://github.com/loki79uk/FS22_UniversalAutoload/blob/2347d525eb5eb76fb39035fd1e4d947ead7ac525/UniversalAutoloadInstaller.lua#L187

Try replacing it with the default settings file again and see if that works.  Otherwise the only thing I can think of is something to do with OneDrive?

**Comment by ggoosen** [comment] 2024-06-19 09:05
This is the full file, it works when i add it to "default" items.

`<?xml version="1.0" encoding="utf-8" standalone="no"?>


<universalAutoload showDebug="false" highPriority="true" manualLoadingOnly="false" disableAutoStrap="false" pricePerLog="0" pricePerBale="0" pricePerPallet="0" minLogLength="0">

	
    <vehicleConfigurations showDebug="false">
	
	
	

	
	
	
	<vehicleConfiguration configFileName="data/vehicles/salek/ans1900/ans1900.xml" selectedConfigs="2">
		<loadingArea offset="0 0.589 -0.444" width="1.35" height="1" length="2.3"/>
		<options enableRearLoading="true" enableSideLoading="true" showDebug="true"/>
	</vehicleConfiguration>

	

		
    </vehicleConfigurations>
	
    <containerConfigurations>
		
		
		
		

				
		
		
		
		
		
		
		
		
		
		
		
		

    </containerConfigurations>
	
	
	
			
		
		
	
	
</universalAutoload>
`

mods are physically located here ->

C:\Users\georg\OneDrive\Documents\My Games\FarmingSimulator2022\mods

while the default vehicles are here

F:\Program Files (x86)\Steam\steamapps\common\Farming Simulator 22\data\vehicles


Could it be that  that the script is assuming the path as being on C: or F:?

**Comment by loki79uk** [comment] 2024-06-19 09:11
It uses the game path, so the "modSettings" folder that is in the same folder as your savegames and log file are created.

by default:
`%userprofile%\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml`

**Comment by ggoosen** [comment] 2024-06-19 09:27
Fixed it was a syntax issue. Didnt close the " on the file name


Fixed version

`
<vehicleConfigurations showDebug="false">







<vehicleConfiguration configFileName="data/vehicles/salek/ans1900/ans1900.xml" selectedConfigs="2">
	<loadingArea offset="0 0.589 -0.444" width="1.35" height="1" length="2.3"/>
	<options enableRearLoading="true" enableSideLoading="true" showDebug="true"/>
</vehicleConfiguration>



	
</vehicleConfigurations>

<containerConfigurations>
	
	
	
	

			
	
	
	
	
	
	
	
	
	
	
	
	

</containerConfigurations>



		
	
	
`

**Comment by loki79uk** [comment] 2024-06-23 18:16
Is this working okay for you without adding a specific mode?  I've recently started working on UAL 2.0, so depending how that goes I will try to add other vehicle types there.

**Comment by ggoosen** [comment] 2024-06-24 03:05
Specific mode? Like having it classified as a bale trailer? Yes it works
fine

It works yes, although my challenge is actually now with the teleport not
working and also when I go over bale triggers that auto ‘import’ the bales
the trailer sometimes thinks the bales are still in but they have already
left.

**Comment by loki79uk** [comment] 2024-06-25 19:37
> Specific mode? Like having it classified as a bale trailer? Yes it works fine It works yes, although my challenge is actually now with the teleport not working and also when I go over bale triggers that auto ‘import’ the bales the trailer sometimes thinks the bales are still in but they have already left.

So it isn't working okay then! lol

I'll see what I can do to improve it

**Comment by ggoosen** [comment] 2024-06-26 02:27
Sorry, I mixed a whole bunch of things in there.

The straw overload type trailer is working fine, no issues with that since
we used it.

All trailers using the Autoload mod have issues with the teleport mod, not
supprised here really because i think you would have to handle that
specifically to make it compatible.
The issue i have will bale trailers relates to another mod where it "auto
ingests" the bales, which confuses the trailer to think there are still
bales in the trailer. Perhaps on the "Unload" function force a check to see
if there is anything on the trailer and reset the state.

**Comment by loki79uk** [comment] 2024-06-26 18:18
How is this as a concept? Obviously needs smaller bales, but kind of works..

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/8c8ecd83-05b0-4eb3-8abf-2ca4220f0647)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/7fa0386f-bb0b-43b1-ba2c-0b90a70fceea)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/3ff6cf49-0635-4a55-b9cf-030767f30d33)

**Comment by ggoosen** [comment] 2024-06-27 03:41
Added a few screenshots for you here of the other loader and how it works.

This is what it looks like loading and unloading. Works fine and auto places as per the images. 
![Farming Simulator 22 27_06_2024 11_28_37 AM](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/a6d7e84c-c8b7-4783-bd9c-bafae165e830)

![Farming Simulator 22 27_06_2024 11_27_41 AM](https://github.com/loki79uk/FS22_UniversalAutoload/assets/3011859/2b52e90c-5891-450e-b786-351d3d8c3095)
()

The only thing that would make it any better was if there was a way to put a small gap between the sets of bales like you can see i have manually done in the top 2 rows in this image

![Uploading Farming Simulator 22 27_06_2024 11_29_50 AM.jpg…]

**Comment by loki79uk** [comment] 2024-06-27 15:49
You could create two loading areas, one on each side.

**Comment by ggoosen** [comment] 2024-06-27 22:21
Hmm, will try that and let you know.

Is there an example / document showing how to do that?

**Comment by loki79uk** [comment] 2024-06-27 22:53
> Hmm, will try that and let you know. Is there an example / document showing how to do that?

There are some examples in the base game configs, but you just add two xml tags like this:
```xml
        <vehicleConfiguration configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <loadingArea offset="0 1.010 -0.33" width="2.45" height="2.25" length="11.2" baleHeight="2.8"/>
            <loadingArea offset="0 1.500 6.975" width="2.45" height="2.25" length="3.20" baleHeight="2.8"/>
            <options isBaleTrailer="false" enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>
```

**Comment by loki79uk** [comment] 2024-06-29 11:58
I've added all the base game straw blowers and TMR mixers.  You can use the new features by adding:
```lua
<options isBaleProcessor="true"/>
```
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.5.2.0

**Comment by loki79uk** [comment] 2024-06-29 14:54
Also try this configuration:
```xml
		<vehicleConfiguration configFileName="FS22_StrawBlower_Gyrax_P22700/Gyrax_P22700.xml">
			<loadingArea offset="0 1.35 -1.20" width="1.85" height="1.65" length="5.3" noLoadingIfUnfolded="true"/>
			<loadingArea offset="2.4 1.35 -1.20" width="2.41" height="1.35" length="5.0" noLoadingIfFolded="true"/>
			<loadingArea offset="-2.4 1.35 -1.20" width="2.41" height="1.35" length="5.0" noLoadingIfFolded="true"/>
			<options isBaleProcessor="true"/>
		</vehicleConfiguration>
```

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/3b085c8d-31ff-4634-adf4-8fd5841159dc)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/a37a1576-05ff-443a-b8f3-ef3fd609a5fd)

**Comment by loki79uk** [comment] 2024-07-07 11:07
@ggoosen Have you had a chance to try this yet?

**Comment by ggoosen** [comment] 2024-07-07 23:31
> @ggoosen Have you had a chance to try this yet?

Yep, tested it! Sorry, i thought i had updated the thread. This works perfectly!

**Comment by loki79uk** [comment] 2024-07-08 10:01
Good news! Make sure you update to 1.5.2.1 as there was a bug in 1.5.2.0

**Closed** 2024-07-08 11:01 UTC
