### ISSUE TITLE
When trying to load cypress.

### ISSUE THREAD

**Issue by vitalii2011** [loki79uk/FS22_UniversalAutoload#111] opened 2022-10-18 14:25 UTC
CTD or "game freezes" - no, but the game does not quit.
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/9811404/log.txt)

**Comment by loki79uk** [comment] 2022-10-18 14:41
Thanks for the report - I'm sure I tried spruce, but maybe not.  I have not had any time to test, but the latest release should at least prevent the LUA error.  I will investigate properly later!
https://github.com/loki79uk/FS22_UniversalAutoload/releases

**Comment by DrewCZ** [comment] 2022-10-18 18:39
Hi @loki79uk may I help you with a test? What can I do / try to do if possible?

**Comment by vitalii2011** [comment] 2022-10-18 19:04
> … the latest release should at least prevent the LUA error. 

Now the HUD does not disappear and the game can be controlled. But I would like it to be possible to load any trees (cypresses, pines, etc.) on the contrary. Yes, even with uncut branches. ) Or is it impossible?

**Comment by loki79uk** [comment] 2022-10-18 20:01
> Hi @loki79uk may I help you with a test? What can I do / try to do if possible?

Hi - if you can just play test as much as possible with weird combinations of vehicles, loading different tree types, etc, and report what doesn't work as expected would be great!

**Comment by DrewCZ** [comment] 2022-10-19 19:26
> > Hi @loki79uk may I help you with a test? What can I do / try to do if possible?
> 
> Hi - if you can just play test as much as possible with weird combinations of vehicles, loading different tree types, etc, and report what doesn't work as expected would be great!

Tests: 
1. loading partially delimbed trees and a few branches works well.
2. when cut branches were removed, the tree was loaded twice with branches as expected.
3. tree w/ branches removed, then try load birch, but not possible w/ the message the trailer is full
4. reset using 'ualClearLoadedObjects', no effect (but I think this is not related to trees?)
5. trees must be almost delimbed for the loading (expected behavior?)
6. combination of cut and delimbed oak, spruce, and birch works well (check the pic)
![obrazek](https://user-images.githubusercontent.com/26751314/196784303-ec6a8556-3445-4192-8367-275157a5dd9d.png)

strange combinations of trailers: hope in a few days
no issues in the log
what next?

**Comment by DrewCZ** [comment] 2022-10-19 19:49
one question about log file already posted.
that the first LUA exception isn't related to the game stuck? 
`2022-10-18 17:12 Warning (script): 'getXMLFloat': Argument 1 has wrong type. Expected: Int. Actual: Table 
2022-10-18 17:12   2022-10-18 17:12 D:\auto_builder\cache\svn\1439bdbdb2e647a66733235d7978a817\src\base\scripting\lua\LuaScriptSystem.cpp (838)2022-10-18 17:12 : 2022-10-18 17:12 expectedType == Value::VoidType || expectedType == Value::ObjectType || expectedType == Value::IntArrayType || expectedType == Value::FloatArrayType || expectedType == Value::ArrayType
2022-10-18 17:12 LUA call stack:
  =C:/Users/Mavra/Documents/My Games/FarmingSimulator2022/mods/FS22_InsideCameraZoom/main.lua (11) : getXMLFloat
  dataS/scripts/vehicles/specializations/Enterable.lua (588) : loadFromXML
  dataS/scripts/vehicles/specializations/Enterable.lua (244) : loadCamerasFromXML
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (972) : raiseEvent
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
`
I'm asking because this type of error destroys my game a few times and is the source of unexpected behavior.

**Comment by loki79uk** [comment] 2022-10-19 20:10
> one question about log file already posted.
> that the first LUA exception isn't related to the game stuck?
> I'm asking because this type of error destroys my game a few times and is the source of unexpected behavior.

This error is coming from the mod `FS22_InsideCameraZoom`

There is a function call to `getXMLFloat` (on line 12), and the argument being passed is a table instead of an integer.  Should be easy enough to catch the first argument (probably xml file index) and check the type before proceeding.  Report it to the mod author if you can so he can fix it.

**Comment by vitalii2011** [comment] 2022-10-19 21:59
> what map are cypress trees?

https://farming-simulator.com/mod.php?lang=en&country=gb&mod_id=230836 + https://farming-simulator.com/mod.php?lang=en&country=gb&mod_id=249491

**Comment by loki79uk** [comment] 2022-10-20 22:22
> > … the latest release should at least prevent the LUA error.
> 
> Now the HUD does not disappear and the game can be controlled. But I would like it to be possible to load any trees (cypresses, pines, etc.) on the contrary. Yes, even with uncut branches. ) Or is it impossible?

Logs with branches should load as long as you cut them small enough.  Try turning on the debug view (ctrl-shift-F12) and you should see the size of the bounding box for the wood:

![image](https://user-images.githubusercontent.com/76516343/197070106-c9a215d7-37ba-4817-94fd-38e4638a3270.png)

**Comment by DrewCZ** [comment] 2022-10-21 12:08
> 

Yes, I know, it was only a question if this error can affect the second error from your mod.

**Comment by DrewCZ** [comment] 2022-10-21 12:12
> > one question about log file already posted.
> > that the first LUA exception isn't related to the game stuck?
> > I'm asking because this type of error destroys my game a few times and is the source of unexpected behavior.
> 
> This error is coming from the mod `FS22_InsideCameraZoom`
> 
> There is a function call to `getXMLFloat` (on line 12), and the argument being passed is a table instead of an integer. Should be easy enough to check the type of the first argument (probably xml file index) before proceeding. Report it to the mod author if you can (so he can fix it).

Yes, I know, it was only a question if that first error can affect the second error from your mod. Clear, forget it :)

**Comment by DrewCZ** [comment] 2022-10-21 12:27
>     * 5+6 - I have not even tried partially delimbed trees, but I guess that the bounding boxes become huge and therefore they will not fit.  I wonder if that is the problem in the screen shot too - if you release the tension belts will they fall down, or are they supporting each other with 'phantom' branches?

Yes, exactly, logs don't fall and stay as it is. On the screen were bigger bounding boxes, due to "not properly cut branches". But it was an **intentional state during tests**. If spruce logs (more smooth and without branches and knots) were loaded randomly first, the final load was better. Test with only spruces works great and the trailer was full, almost without spaces. 
💡 Maybe you can test for spruce/pine/narrow/straighten logs (bounding boxes) and load them first then other logs? 
Anyway, loading works well I think at this moment 👍

**Comment by vitalii2011** [comment] 2022-10-22 20:10
Can there be "Auto-Log Mode" for logs/wood?

**Comment by loki79uk** [comment] 2022-10-22 20:37
> * Can there be "Auto-Log Mode" for logs/trees?
I could possibly do a static auto load wood mode, but I don't think it will work like the bale auto collect mode.  That was designed more for CoursePlay than anything, and relies on removing bales from physics.  However, the logs rely on physics to load properly, so it may not work very well.

>     * Can in F1 the maximum length of logs/trees that will be "auto-loaded" into a trailer/logging truck is indicated?
Do you mean just to display the maximum length for the trailer?  or would you like to select the length for loading?

**Comment by vitalii2011** [comment] 2022-10-22 20:56
> to select the length for loading?

The Fliegl Timber Runner didn't load 12m long cypress trees (although it seems to be designed for that length), but with less than ~10.9m everything is fine. If this is possible and not difficult, a certificate of the maximum length of the cargo will probably not be superfluous.

**Comment by loki79uk** [comment] 2022-10-23 16:32
> The Fliegl Timber Runner didn't load 12m long cypress trees (although it seems to be designed for that length), but with less than ~10.9m everything is fine. If this is possible and not difficult, a certificate of the maximum length of the cargo will probably not be superfluous.

I have increased the length on the Timber Runner to 12.1, so that now it takes 12m logs.
I have also added an F1 info item to show the maximum log length.
![image](https://user-images.githubusercontent.com/76516343/197404035-aa74965e-2437-44d6-8da8-b9ced6c1c4dc.png)

**Comment by vitalii2011** [comment] 2022-10-23 20:09
> to 12.1

"12.1 m" will not be a problem after the release of Platinum Expansion?
![Screenshot 2022-10-23 at 23-06-16 Platinum Preview Log Transport feat  Yarders Winches   Containers](https://user-images.githubusercontent.com/41552153/197415762-5ffde74d-3cec-43d2-b7ce-97f9d9b49ecf.png)

**Comment by loki79uk** [comment] 2022-10-23 21:48
> "12.1 m" will not be a problem after the release of Platinum Expansion?

12.1m is only the maximum for the Timber Runner trailer.  The reason it was not loading before is because sometimes the "12m" logs are actually e.g. 12.001m and then it is determined that they would not fit inside a 12m space.  Increasing the sapce to 12.1m prevents any issues like this.

I hope that I can add autoload to those containers as well!

**Comment by loki79uk** [comment] 2022-10-30 21:15
Can I close this now?  For me all of the different tree species seem to load as expected.

**Comment by vitalii2011** [comment] 2022-10-30 22:09
> Can I close this now? For me all of the different tree species seem to load as expected.

Yes, of course. Thank you very much.

**Closed** 2022-10-31 18:44 UTC
