### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LTArt-Jonathan** [loki79uk/FS22_UniversalAutoload#67] opened 2022-06-26 21:56 UTC
ive tried to download it from the ingame mod-hub and its not working. Nothing new is showing up in the F1 menu. 

i have restarted the game, restarted the pc, reinstalled the mod and still nothing... please help

**Comment by loki79uk** [comment] 2022-06-26 22:17
Try resetting your key bindings from the in game settings menu.  This is a known bug that should be fixed in the upcoming patch, but to avoid in the mean time, always restart the game after installing any new mods from the in game ModHub (before launching a save game)

**Comment by loki79uk** [comment] 2022-07-01 20:13
Closing for housekeeping - if it is not your keybindings, try running UAL as the only mod and add others back in to see where the problem is.

**Closed by loki79uk** 2022-07-01 20:13 UTC
