### ISSUE TITLE
Unable to load more than 4 pallets

### ISSUE THREAD

**Issue by ouyin2000** [loki79uk/FS22_UniversalAutoload#72] opened 2022-07-21 01:49 UTC
![FS22 screenshot](https://user-images.githubusercontent.com/50339219/180111911-edaa2b6e-ce71-4110-bea0-46ae983915c4.jpg)

So it seems I'm unable to autoload more than 4 pallets. Ive tried this with both modded trailers and vanilla ones. Also with all mods disabled. I hit LShift+R as the instruction says, and this is the result. Surely it's possible to carry more than that??

**Comment by loki79uk** [comment] 2022-07-21 06:53
The boxes around the pallets show the defined size (probably from the pallet xml).  You need to define them to the correct size.  They are set as very tall, but also too big in x and y which is why they are not packing very closely together.

**Comment by loki79uk** [comment] 2022-07-21 09:00
On closer inspection (PC browser, not phone), I can see the width and length are also switched, so the boxes do not line up at all with the dimensions of the pallets.  What are the mod pallets you are using?

**Comment by ouyin2000** [comment] 2022-07-23 03:02
OH! I hadn't considered that the pallets would be the problem. The pallets of planks are from the Calm Lands map included, edited sawmill. I'm also using the Storage Shed for Products on Pallets mod to hold pallets of planks until I'm ready to bring to market.

**Comment by loki79uk** [comment] 2022-07-24 20:30
Have you managed to create a configuration for these pallets in your local user settings?  I've been quite busy over the last few days, but if you are still having trouble I'll have a look at it for you.

**Comment by ouyin2000** [comment] 2022-07-25 01:50
I haven't been able to take a look at it. Been a busy few days. I'm not in a rush, though. Thanks for your assistance!

**Comment by loki79uk** [comment] 2022-08-05 18:26
Closing as not a bug, but feel free to contact me on Discord if you are still having trouble defining the pallets: Loki_79#2864

**Closed by loki79uk** 2022-08-05 18:26 UTC
