### ISSUE TITLE
Add ability to increase or decrease the length of both the trigger area and the loading area simultaneously

### ISSUE THREAD

**Issue by HatsuneKid** [loki79uk/FS22_UniversalAutoload#219] opened 2024-02-03 03:24 UTC
Hi, I want to adjust the front and rear starting positions of the loading area on a semi-trailer to optimize the mass position of the cargo in the game. And I did achieve it by using [ lengthAxis="xxx" ] & [ offsetRoot="xxx" ] Or rather, shorten the length of the loading area while moving the offset point of the loading area backward.
But there is a problem.
Now its operating logic is that the length of the loading area can only increase but not decrease, and the **initial trigger area length is consistent with the loading area length and cannot be changed**. I can use reverse animation to reduce the length of the loading area, but doing so will result in the initial trigger area being too short which is inconvenient for full length loading.

**Comment by loki79uk** [comment] 2024-02-03 10:21
The reason I kept the triggers fixed was that I was worried it may not detect items entering/leaving the trigger during the resize process,  I don't know how the engine detects collisions, and maybe it won't count if the trigger changes size.  It may not be a problem, so I'll see if I can set up a test to prove it would work.

**Comment by loki79uk** [comment] 2024-02-03 10:38
Did you make the negative 'spec_cylindered.movingTools' as a workaround, or is it likely to happen in other cases?  Would it just work if I had a direction flag for the movement?

**Comment by HatsuneKid** [comment] 2024-02-03 10:57
Perhaps the trigger does not need to changed size.
Adding a direction flag for the movement might work I think. Allowing the loading area to be reduced in size while keeping the initial size of the trigger is wonderful

**Comment by HatsuneKid** [comment] 2024-02-03 11:07
I did make the negative 'spec_cylindered.movingTools' as a workaround. Cause I want to move the starting position of the loading area backwards while reducing its size.
This seems to require a code to specify that I am controlling the front movement of the loading area.

**Comment by loki79uk** [comment] 2024-02-03 11:14
Please try this one [FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/14151163/FS22_UniversalAutoload.zip)
I have not committed it yet, but the only change is to add three new flags for the loading areas: 
`reverseWidthAxis="true" `
`reverseLengthAxis="true" `
`reverseHeightAxis="true" `

**Comment by HatsuneKid** [comment] 2024-02-03 12:57
It work!
And is there a better way to simply move the front of the loading area backward?

**Comment by loki79uk** [comment] 2024-02-03 13:03
I'm not sure how you mean, do you want it to move with the control axis, or just to define an offset for the starting position?

**Comment by HatsuneKid** [comment] 2024-02-03 13:14
Yes I mean I want to move the front of the loading area backward with the control axis in game. Sometimes I need to load just a few heavy pallets in the middle of the trailer so I came up with this solution.

**Comment by loki79uk** [comment] 2024-02-03 13:40
> Yes I mean I want to move the front of the loading area backward with the control axis in game. Sometimes I need to load a few heavy pallets in the middle of the trailer so I came up with this solution.

So even with the layer stacking the pallets are too heavy to be loaded at the front?

I could certainly add a 4th option to move the front only with an axis control, so instead of `lengthAxis`, you could use e.g. `offsetLoadingPositionFrontAxis="someAxis"` with optional `reverseOffsetLoadingPositionFrontAxis="true"` and that would only move the front position back without moving the back. Is that what you actually asked for in the first place? :D

**Comment by HatsuneKid** [comment] 2024-02-03 13:42
> > Yes I mean I want to move the front of the loading area backward with the control axis in game. Sometimes I need to load a few heavy pallets in the middle of the trailer so I came up with this solution.
> 
> So even with the layer stacking the pallets are too heavy to be loaded at the front?
> 
> I could certainly add a 4th option to move the front only with an axis control, so instead of `lengthAxis`, you could use e.g. `offsetLoadingPositionFrontAxis="someAxis"` and that would only move the front position back without moving the rear position. Is that what you actually asked for in the first place? :D

Yes yes yes!

**Comment by loki79uk** [comment] 2024-02-03 13:52
Okay, so I think I will call it `offsetFrontAxis` as the other name is too long.  I think there is a use case to have both lengthAxis and offsetFrontAxis active at the same time, as long as they use different `spec_cylindered.movingTools`.

**Comment by loki79uk** [comment] 2024-02-03 13:53
Can you think of a use case for moving the rear position as well?  I'm not sure that would ever be as helpful, you can always just stop loading if you want to.

**Comment by HatsuneKid** [comment] 2024-02-03 14:11
For some special vehicles with extendable tails, movable rear position of loading area is more like an automated mechanism that eliminates the need for players to manually stop loading I think. It is not necessary but it could provide convenience or playability. Maybe someone could use this feature to implement new ideas.

**Comment by loki79uk** [comment] 2024-02-03 15:26
I don't have time to test this properly now, but if you could try it and let me know, that would be really helpful! :D

[FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/14151977/FS22_UniversalAutoload.zip)

All three should work together, even on the same axis: `lengthAxis`, `offsetFrontAxis` and `offsetRearAxis`

I could have easily got the directions mixed up though!   Only `lengthAxis` should be affected by setting `reverseLengthAxis="true"`.

**Comment by HatsuneKid** [comment] 2024-02-03 16:46
Bad news. 
Testing `offsetFrontAxis="AXIS_CRANE_TOOL2"` and `offsetRearAxis="AXIS_CRANE_TOOL2"`
Both offsetFrontAxis and offsetRearAxis are not working. Nothing changes in game. And no error displayed.
Testing `offsetFrontAxis="AXIS_CRANE_TOOL2" lengthAxis="AXIS_CRANE_TOOL2"` together
It shows that the whole loading area and trigger can move but the actual loading position is in the rear positions and can not be moved. The loaded pallets are even placed on the ground behind the trailer although it's already beyond the loading area, and they are still considered loaded by the trailer and can be unloaded.

**Comment by HatsuneKid** [comment] 2024-02-03 16:58
Testing `offsetFrontAxis="AXIS_CRANE_TOOL2" offsetRearAxis="AXIS_CRANE_TOOL2"` together
Nothing changes in game. Unable to use axis controls to move the loading area.
All codes involved:
```
        <animation name="loadStartLine">
            <part node="0>0|3|0|0|0|16|1" startTime="0" endTime="2" startTrans="0 0 0" endTrans="0 0 -6"/>
        </animation>
...
            <movingTool node="0>0|3|0|0|0|16|1">
                <controls axis="AXIS_CRANE_TOOL2" invertAxis="false" mouseSpeedFactor="0.8" iconName="WORKING_WIDTH_TRANSLATE_X" />
                <animation animSpeed="0.4" animAcceleration="100" animName="loadStartLine" />
            </movingTool>
...
            <vehicleConfiguration>
                <loadingArea offset="0 1.185 -0.1" width="2.40" height="2.20" length="13.2" baleHeight="2.60" offsetFrontAxis="AXIS_CRANE_TOOL2" offsetRearAxis="AXIS_CRANE_TOOL2"/>
                <options enableRearLoading="true" enableSideLoading="true" isBaleTrailer="false"/>
            </vehicleConfiguration>
```

**Comment by HatsuneKid** [comment] 2024-02-03 17:13
The functions of `lengthAxis` and `offsetRearAxis` is duplicate so that one of them can be removed I think. Perhaps their coexistence can cause conflicts.

**Comment by loki79uk** [comment] 2024-02-03 18:24
Maybe faster to talk about this on Discord?  Loki_79

**Comment by loki79uk** [comment] 2024-02-03 19:57
I found where it was going wrong.  I had a check for `loadArea.lengthAxis ~= nil`, but I didn't add the new options there.  I'm adding the option to use rotation as well now, so I'll post a new version later today.

**Comment by loki79uk** [comment] 2024-02-03 22:03
This is working for me now, but needs some refinement:  [FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/14154387/FS22_UniversalAutoload.zip)

Try with this forestry vehicle, and open/close the grabber jaws:
```xml
        <vehicleConfiguration configFileName="data/vehicles/kesla/nd122/nd122.xml">
            <loadingArea offset="0 1.50 -0.80" width="2.20" height="1.4" length="5.1" offsetFrontAxis="AXIS_CRANE_TOOL"/>
            <options isLogTrailer="true"/>
        </vehicleConfiguration>
```

**Comment by HatsuneKid** [comment] 2024-02-04 03:00
Testing on that vanilla forestry vehicle. Opening/closing the gripper jaws has no effect on both the loading area and the actual loading position of the logs. 
Testing on a rework trailer base on vanilla Krone ProfiLiner. In order to use **Interactive Control** to open its side curtain, I set its autoload  to be a regular flatbed trailer.
```
            <vehicleConfiguration>
                <loadingArea offset="0 1.185 -0.1" width="2.40" height="2.20" length="13.2" baleHeight="2.60" offsetFrontAxis="AXIS_CRANE_TOOL2"/>
                <options enableRearLoading="true" enableSideLoading="true" isBaleTrailer="false"/>
            </vehicleConfiguration>
```
Now I can move the front of the loading area with axis control. It looks good in debug mode.
But the actual loading area of the pallet is offset backwards by half the length of the initial loading area.
I observed there's a white line at the middle bottom of the loading area which is also the starting point for pallet loading now.

A secondary suggestion is that if the size of the trigger remains unchanged when I move the front of the loading area, then it would be even better if the position of the trigger remains the same.

By the way, `offset="0 1.10 -0.80"` may suitable for KESLA 144ND cause its bottom is concave :)
Due to some complex reasons, I currently do not have Discord account.

**Comment by loki79uk** [comment] 2024-02-04 08:55
I never actually tested loading, just that the zones moved in the debugger view.   It is odd that it doesn't work at all for you though?

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/c4b39df0-8845-4b4d-b50b-4a4262c364f5)

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/18d95806-9a87-42b6-929d-43814c9a8eca)

The reason I didn't drop the zone down so low on that once, is that if you are not careful it can detect ojects OUTSIDE of the trailer as "loaded".

**Comment by loki79uk** [comment] 2024-02-04 09:13
I see the issue with the starting position, I'll have a look at it now.

**Comment by loki79uk** [comment] 2024-02-04 11:21
I think this is getting close to working now:  [FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/14156485/FS22_UniversalAutoload.zip)

**Comment by HatsuneKid** [comment] 2024-02-04 13:09
Everything works fine now, thanks!
We can now control the loading position of goods to achieve better load distribution and improve the driving experience for vehicles, not by manually loading but autoload!

**Comment by loki79uk** [comment] 2024-02-04 13:15
Awesome - I think there are some more refinements possible:

- Currently the 'old' length/height/width axis can only be controlled by something that moves in the same direction (it was designed for the extendable flat loaders).  Do you think it would be useful to make it any axis?
- We still need a way to define the distance for movements controlled by rotation (currenly mapped to 0-1, but we could pass in a distance somehow)

**Comment by HatsuneKid** [comment] 2024-02-04 14:13
- Since it is now possible to control the movement of the front and back of the loading area separately, length with axis control is less important I think. Axis control of width and height could serve as a redundant function. Although trailers and vehicles with extended forms are not common.
- Considering that I prefer to use highly customized mod vehicles in fs22, I couldn't think of any use cases that require defining the distance for movements controlled by rotation.

**Comment by HatsuneKid** [comment] 2024-02-05 05:19
After repeated testing, I have concluded that `offsetFrontAxis` and `offsetRearAxis` can only be used to **shorten** the length of the loading area from the front and rear. `lengthAxis` is used to **extend** the length of the loading area from rear. Shortening and lengthening are relative to the trigger that maintain the same length. I finally understand their function completely.
Making length/height/width also move on different axis is quite useful but only for few special vehicles and the players who value precise operations.

By the way, Neither `heightAxis` nor `widthAxis` worked in my test. 
In addition, after using `lengthAxis` to extend the loading area, the trigger used to recognize the pallets on the vehicle still maintains its initial length, making it unable to recognize the front and back pallets of the vehicle, resulting in inconvenience during unloading. But I don't have any use cases for `lengthAxis` on any vehicle. Just found that it may cause inconvenience.

**Comment by loki79uk** [comment] 2024-02-05 10:04
Height and width are restricted to things that actually move in those directions.  Maybe I should open it up.  Moving the wrong way is probably better than not moving.

For an example of an extending trailer, try one of the low loaders that came with the platinum/forestry dlc.  That is the reason I added the feature.

I'm busy with other things for a few days, but I'll work on finalising a new release of UAL.

**Comment by HatsuneKid** [comment] 2024-02-05 11:05
I think of some trailers with cover which can provide a higher or wider pallet loading area when opened. This means that it's need to associate the change in loading area height/width with the cover animation which seems hard to achieve.

**Comment by HatsuneKid** [comment] 2024-02-06 02:24
Cool. I suddenly realized that `heightAxis` and `widthAxis` didn't work because I forgot to set the corresponding translation axis in animation paragraph. Now they work.

**Comment by loki79uk** [comment] 2024-02-10 10:22
I am just designing a new feature that may help you actually, although it will apply to the pallet and so will affect ALL trailers equally so maybe not as good.

The idea is to add an offset to certain pallet types, but ONLY when they are loaded first onto a trailer.  If you set this to be a multiple of the pallet size, then it should start in the middle, fill to the back, and then fill in at the front again.

Does that sounds like it could work for your heavy pallets?

**Comment by loki79uk** [comment] 2024-04-06 16:54
Closing as fixed.

**Closed by loki79uk** 2024-04-06 16:54 UTC
