### ISSUE TITLE
Weird Bale Stacking Issue

### ISSUE THREAD

**Issue by RobTomcat** [loki79uk/FS22_UniversalAutoload#30] opened 2022-03-08 19:26 UTC
Hi Loki.  Trust me to find another bale stacking issue!

Using you most recent update, v013 labelled tweaked loading logic, my DPW 1800 Bale Trailer now occasionally, but not always, loads 4 bales high.  See attached pic. I have not changed the parameters for this trailer as I saw you had changed the height on it.  Normally it now consistently loads 3 bales high and 21 x 220cm hay bales.  However, since your most recent update "tweaking loading logic" I occasionally get it loading 4 bales high and then it becomes inconsistent with where it loads further bales.  There is an easy get around.  I just unload it in place and then reload and always it loads correctly 3 bales high everywhere.

Something else.  I went to the Biogas Heating plant loaded with silage bales and could not get the trailer to unload either automatically over the pit as usually happens or manually (using I).  It kept telling me "space is occupied".  I tried several times and in different directions without success and both over the pit and to the side of it.  In the end I just pushed the bales off the trailer with super strength and of course they disappeared into the pit.  Not sure if this is an issue with your mod or with the Biogas Plant.

Edit - I should add I have not had any problems unloading bales at the Farmers Market in Haut Beyleron.  They simply unload automatically without my intervention.

![Bale Trailer Sstacking 4 High](https://user-images.githubusercontent.com/99221276/157310225-89aa4f99-8bdf-4598-a3c0-9e6458f7f399.jpg)
.

**Comment by loki79uk** [comment] 2022-03-10 12:42
Hi, sorry I've not been watching this and don't seem to have an email from GitHub even though I get others?  Anyway, if you can reproduce it, or next time it happens can you turn on the debugging display and take a screenshot please.  Is it only when loading bales?

**Comment by RobTomcat** [comment] 2022-03-10 12:59
No bales at the moment. Will see if I can reproduce it later with a log.

Any info on the Biogas Heating unload issue?  I am sure it is to do with the Biogas plant unload grill on Haut Beyleron rather than your mod.  Most of the bale and pallet unloads are onto a fixed concrete unload point - as at the Farmers Market -whereas the Biogas Heating plant unload is onto a grill - like for grain.  Maybe your mod does not like "grills" and thinks it is an object in the way of unloading.

**Comment by loki79uk** [comment] 2022-03-10 13:13
Yeah, it is probably viewing the grill as an object, but could also be detecting the trigger as an object.  It should depend on the height, so if it is lower than the bed of the trailer then it should unload.  Try the debug output and see if the unload boxes change height?  I'll look this evening after work as well.

**Comment by RobTomcat** [comment] 2022-03-10 14:29
Certainly the grill was lower than the bed of the trailer.  Again no bales at the moment to test but will try later.

**Comment by RobTomcat** [comment] 2022-03-10 18:50
OK, I have been able to re-create my bales from a save shortly before I baled and I appear to be able to reproduce the situation each time.  I am loading 2 bales onto the back of the trailer(!), then 2 more on top of these making it 4 high, and then no more bales can be loaded.  Will take some pictures.

How do I turn on the debugging display please and what info so you require from it?  Do you want the display before or after the loading of the 4 bales?

**Comment by loki79uk** [comment] 2022-03-10 19:21
Ahh, sorry - I sent you some messages on Discord. I think I've solved it.  Now I'm working on the new bugs that the solution introduced.. :D

**Comment by loki79uk** [comment] 2022-03-10 22:45
Hopefully fixed now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-014

**Comment by RobTomcat** [comment] 2022-03-11 09:53
I can confirm update 014 resolves the initial bale stacking issue with bales only loading to the back of the trailer, thanks.

Regarding unloading bales at the Biogas Heating Plant on H-B, that has not been resolved as yet.  FS22 still tells me the unloading area is blocked when trying to unload on the unloading grill point.  Yes I can unload the bales at the info trigger next to the unload grill as you suggested or to the side of the unloading grill, but the bales then still need to be moved with super strength to the unloading grill to disappear and to be recorded as sold.

**Comment by ddewar** [comment] 2022-03-11 15:28
The unloading issue is due to the mod needing a place to set the bales. It will not just drop them. I think it's more of an issue with the BGAs triggers being over the mixing machines.

**Comment by loki79uk** [comment] 2022-03-11 22:26
There is definitely a big invisible object over the fill point. I'll have a look to see what the collision flags are in the editor now. 

![image](https://user-images.githubusercontent.com/76516343/157981245-30fe1e39-06cf-4fee-aa0d-d819f842c0ee.png)

**Comment by loki79uk** [comment] 2022-03-11 23:10
Nothing in the map or the model there, so I'm stumped of where else to look?  

![image](https://user-images.githubusercontent.com/76516343/157986585-cdea76c9-7656-4580-8dc2-b6147102ced7.png)

**Comment by RobTomcat** [comment] 2022-03-12 07:54
Don't worry about it Loki as it seems very difficult to resolve.  I am just wondering if there is anywhere else that has a grill we may wish to unload over.  Most of the places we would unload pallets/bales are solid concrete with the unload icon over the top.  Grills are normally to unload grain into, not bales.  Just have to remember we cannot auto unload onto a grill.

**Comment by loki79uk** [comment] 2022-03-12 10:46
This should hopefully fix the unloading:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-016

I tested on the BHP building (the one in the pictures above) and the thing that fixed it was removing `CollisionFlag.TREE` so I have no idea what is going on there?  Even more strange is that trees still block the unloading, so wtf.. 🤷‍♂️

**Comment by RobTomcat** [comment] 2022-03-12 13:04
Um yes, that's great, I could manually unload the bales with "I" no problem, either on the grill or to the side of the grill, BUT there is now another issue.  The unload point will not accept the bales either unloaded directly off the trailer - 1st picture - or if I used super strength - 2nd picture - to move them around a bit!

It's a case, unfortunately, of fix one issue to cause another.

![Bales unloaded](https://user-images.githubusercontent.com/99221276/158018922-8eb2402b-3155-47b1-88fc-01dc30853423.jpg)

![Bales unloaded and super strength](https://user-images.githubusercontent.com/99221276/158018931-0df6e72e-89d4-4455-aab3-499827954dea.jpg)

**Comment by loki79uk** [comment] 2022-03-12 13:32
That is weird, do they load if you crash into them so they move?  Or of you unload while moving?  Maybe they just need to be raised active to sell?

**Comment by RobTomcat** [comment] 2022-03-12 14:00
I unloaded while stationary.  In fact I unloaded and reloaded several times in slightly different positions.  None of the unloads would disappear to sell.  The 2nd picture above is where I have used super strength to move them - no change.

I attach my save file from the 2nd picture above for you to check.  You can press "I" and all but 2 of the bales will reload automatically and you have to move a little closer to get the furthest 2.  Better for you to check I think so you can try multiple options as I cannot get them to sell - I am probably simply missing something!

[savegame2 - Loki BHS KEEP.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/8237709/savegame2.-.Loki.BHS.KEEP.zip)

**Comment by loki79uk** [comment] 2022-03-12 14:48
Do they sell if you save and reload?  Or is it just full, so not accepting any more?

**Comment by RobTomcat** [comment] 2022-03-12 15:16
No.  That save file I sent you above is a save and I have reloaded it to test it before sending to you.  The bales will not sell and it is not possible to see if the place is full - no info comes up on the "i" logo or on the place itself.

I just tried again what I did the first time I became aware of the issue reported above.  I drove the trailer to the side of the BHS, unloaded all the bales onto the concrete and then took them with super strength to the grill.  They would not disappear and sell.  In my original post above they did disappear and sell when I did this.  So has something in your mod affected/changed the BHS "unload" point so it will no longer accept bales?

You should try with the save I sent you above and you can experiment with anything you wish to try to identify the issue.

**Comment by loki79uk** [comment] 2022-03-12 15:31
I'll try when I get home, but sell points should not be affected at all by my mod.  Try without any mods, or go into the savegame placeables.xml and reduce the amount of hay or whatever fill type is stored at the sell point.

**Comment by RobTomcat** [comment] 2022-03-12 15:37
Thank you for trying later today.  I won't be around after 5.00pm today.  As far as I know you cannot buy the Biogas Heating Plant and it does not have a fill limit.

**Comment by RobTomcat** [comment] 2022-03-12 15:56
I just reloaded that save above with no other mods except your UniversalAutoload.  Tried unloading/reloading the bales (together with  super strengthening them) several times at the BHP with no change.  No bales will sell.

Then, to check, took all the bales down to the Farmers Market and after pressing L to remove the straps, all the bales auto unloaded with no problems onto the solid concrete.

**Comment by ddewar** [comment] 2022-03-12 15:58
Sorry, I don't want to be that guy, but I loaded up your save game with as many mods as I had that you had. It looks like the BGA isn't accepting bales right now? I had the same issue in my Elm Creek save. One day one of the places just stopped accepting silage. Could that be the issue? I took the bales to the animal shop and they sold there.

![image](https://user-images.githubusercontent.com/15822357/158025194-0c9cd5d3-f7d0-49fc-920c-11bac3b2f8db.png)

**Comment by RobTomcat** [comment] 2022-03-12 16:00
@ddewar Thanks.  Sounds like a very similar issue.  I'll let Loki see if he can figure out the BHP issue later today.

**Comment by loki79uk** [comment] 2022-03-12 18:56
I get the same as @ddewar.  A brand new savegame on Haut-Beyleron and BHP only takes straw, not hay, grass or silage.

**Comment by RobTomcat** [comment] 2022-03-13 09:59
This is very weird.  I have just checked and the BHP on my map is no longer taking hay so that explains why I cannot sell the bales there.

But it DID take silage bales originally otherwise I would not have gone there in the first place.  

In my original post I stated:
 " I went to the Biogas Heating plant loaded with silage bales and could not get the trailer to unload either automatically over the pit as usually happens or manually (using I). It kept telling me "space is occupied". I tried several times and in different directions without success and both over the pit and to the side of it. In the end I just pushed the bales off the trailer with super strength and of course they disappeared into the pit. Not sure if this is an issue with your mod or with the Biogas Plant."

So the silage bales were accepted and sold there finally and I checked before trying to sell hay bales and it offered a better price than the Farmers Market so I went to the BHP to try and sell the hay.

This appears similar to @ddewar saying a place on Elm Creek suddenly stopped accepting silage.  The BHP (the plant in the north of H-B, not the Biogas Plant in the south of H-B) for me which accepted silage from me and said it would accept hay has stopped accepting either.

**Comment by loki79uk** [comment] 2022-03-13 10:11
I wonder if they changed it in the 1.3 patch?  It makes sense that you would not burn hay for heat, it is too valuable as animal feed.  I guess you could burn straw as 'organic waste', so maybe just an oversight when they first set the map.  It sucks that now there is only one sell point for hay on that map though.

**Comment by RobTomcat** [comment] 2022-03-13 11:31
I agree.  So I think you can close this thread because the situation now appears to have changed.  No point in you spending more time when we cannot duplicate the original state.  Thanks for all your efforts.

**Closed** 2022-03-13 13:37 UTC
