### ISSUE TITLE
Stack in two rows

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#85] opened 2022-08-16 11:52 UTC
Is it possible to load a row first and then stack it?

**Comment by loki79uk** [comment] 2022-08-16 14:31
I'm not sure I undertand what you want.  Do you mean a horizontal first loading pattern, the same as this bug? #83

**Comment by loki79uk** [comment] 2022-08-22 11:05
Duplicate of #83 - I think this is a duplicate, but please re-open with more details if not.

**Closed by loki79uk** 2022-08-22 11:05 UTC
