### ISSUE TITLE
[Enhancement] Make the maximum log lengths longer for forwarders

### ISSUE THREAD

**Issue by JukeStuff** [loki79uk/FS22_UniversalAutoload#112] opened 2022-10-24 12:42 UTC
Hey the Forwarders currently can only do 5 meter logs in-game, but it should be around 6 meters. In real life here where the John Deere and Ponsse Forwarders are made the stantard legnth for "logs" is 5.5 meters, but they would be able to do 6m logs easily the limit is 5.5m since it works better with logging trucks only having good space for 5.5m logs.
![image](https://user-images.githubusercontent.com/113805245/197527424-e1f3600d-b811-43d6-a765-3b9f65a0508d.png)

**Comment by loki79uk** [comment] 2022-11-04 10:23
Closing this now as not a bug (and maybe fixed if the issue was rounding numbers in the display).  If you want to chage any of the loading dimensions you can simply copy the settings to your local mod configuration file and increase the loading length for that vehicle.  You will also need to increase the length offset by half the amount you added.

**Closed by loki79uk** 2022-11-04 10:23 UTC
