### ISSUE TITLE
Issues with loading bales

### ISSUE THREAD

**Issue by Bovrinox** [loki79uk/FS22_UniversalAutoload#82] opened 2022-08-06 09:15 UTC
Any ideas why its loading bales like this?
![image](https://user-images.githubusercontent.com/63093402/183242790-ad0efd6e-7a89-4dd3-9e99-fdfff239b921.png)
If I move the stacks closer together after loading it will then load the next 3 like this:
![image](https://user-images.githubusercontent.com/63093402/183242880-d1742ad6-5d4f-4505-b81a-3fd5f24fcb7f.png)
But still wont let me fill the trailer. I can throw the last 3 bales on to get this:
![image](https://user-images.githubusercontent.com/63093402/183242950-f728736f-38d9-4471-b356-c04c4730852e.png)
But then for some reason it wont let me put straps over it, it just takes them off automatically.
It will happily load the smaller bales correctly, like this
![image](https://user-images.githubusercontent.com/63093402/183243084-ca6adad3-3114-44cf-b089-b11a7d684f95.png)
![image](https://user-images.githubusercontent.com/63093402/183243087-c14e9029-3297-49c1-980a-37880cee851b.png)

Hope you can tell what i mean, not easy to explain!

**Comment by loki79uk** [comment] 2022-08-06 10:57
It looks like the bales are not defined properly - can you turn on the debugging (shift-F12) and the outlines around the bales should be just bigger than the bales, e.g.:
![image](https://user-images.githubusercontent.com/76516343/183245915-9b953175-4707-4673-93ab-1f3a87fd49fc.png)

If they are not defined properly, then you will have to add them in your user settings file (with the correct mod/map name), e.g.:
```
<containerConfiguration containerType="BALE" name="FS22_ModOrMapName:squarebale120" sizeX="0.455" sizeY="0.355" sizeZ="1.20"/>
<containerConfiguration containerType="BALE" name="FS22_ModOrMapName:squarebale180" sizeX="1.210" sizeY="0.910" sizeZ="1.80"/>
<containerConfiguration containerType="BALE" name="FS22_ModOrMapName:squarebale220" sizeX="1.210" sizeY="0.910" sizeZ="2.20"/>
<containerConfiguration containerType="BALE" name="FS22_ModOrMapName:squarebale240" sizeX="1.210" sizeY="0.910" sizeZ="2.40"/>
```

**Comment by Bovrinox** [comment] 2022-08-06 11:01
Ah OK ill look into that once I get back to my computer. It is a trailer I
have added your script to myself as per your very helpful readme, but I
tested it with one in the base game and strangely it packs them correctly
in the auto bale collect mode, but not if I park up and load them by hand,
or park next to a pile and activate the regular autoload function.

**Comment by loki79uk** [comment] 2022-08-06 11:28
In that case, check the position of the loading zone as well.  It should be just above the surface of the trailer, and not touching the trailer at the edges.  If there are any collisions with parts of the trailer, then the bales will move and interfere with the next loading position.  This doesn't happen in the bale collecting mode because there are no collisions while that mode is active.

**Comment by Bovrinox** [comment] 2022-08-06 12:32
Ahh OK that makes sense. I'll double check that and the size of the bales,
thanks

**Comment by Bovrinox** [comment] 2022-08-07 13:16
So I have been fiddling about with it a bit, got it working much better by adding the custom size definitions into the config files in your mod, not perfect yet but better!

I added your autoload script to the mod xml files, is it better to add the trailer into the configs in your mod instead? New to using xml, but I'm getting there haha
Thanks a lot for your help

**Comment by loki79uk** [comment] 2022-08-07 17:20
You shouldn't need to add them to the actual mod, but you can do it that way if you prefer - the idea of that is so that the original vehicle modders can add compatibility if they want to.

For single player, the easiest solution is to edit you local mod setting file.

For MP the best solution is to reqest to add the settings to the Add-on mod:
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon#readme

For the console command, you need to edit the local mod setting file.  But as long as the vechile mod is not zipped, then you should be able to use the standard reset vehicle command, reset using EasyDev or just reset at the shop.

**Comment by Bovrinox** [comment] 2022-08-07 18:46
Ah ok, I see what you mean. 
Thanks a lot for your help!

**Comment by loki79uk** [comment] 2022-08-10 08:20
Closing as not a bug, but please message me on Discord if you are still having trouble with configurations: Loki_79#2864

**Closed by loki79uk** 2022-08-10 08:20 UTC

**Comment by Bovrinox** [comment] 2022-08-10 16:59
Nice one, will do thanks mate. 
Mod is awesome BTW, good work
