### ISSUE TITLE
Issue loading small square straw bales

### ISSUE THREAD

**Issue by jaco-dutoit** [loki79uk/FS22_UniversalAutoload#224] opened 2024-03-17 20:01 UTC
I was trying to load small (120cm) square straw bales onto the Welger DK 115 trailer in bale configuration. I enabled auto load and carried the bales one by one to the trailer. After fully loading the trailer I disabled auto load and the tension belts seemed to "miss" some bales when tightening. Trying this a 2nd time to take screenshots the bale below seemed to not support the bale above it and it dropped into the bale below position. 
![Screenshot 2024-03-17 214854](https://github.com/loki79uk/FS22_UniversalAutoload/assets/56035627/5fa11ae3-7dce-4638-9e82-46825aaa54e5)

I tried unloading the trailer and the "missed" bales just floated in the air. When hovering over them they also did not show the info menu and I was unable to interact with them at all. I enabled auto load again and as the trailer was busy loading it placed another bale in the slot occupied by this floating bale.
![Screenshot 2024-03-17 214913](https://github.com/loki79uk/FS22_UniversalAutoload/assets/56035627/3cee8979-b36f-4fc0-b47e-d443876fa0da)
![Screenshot 2024-03-17 215028](https://github.com/loki79uk/FS22_UniversalAutoload/assets/56035627/db648ace-47f5-4e49-9ecb-8aea665b7870)
Debug mode does not show the bale as being registered on the trailer

I tried existing the game and the whole game just froze up. I could see the map clearly but without any tractors, tools or implements. I could also not move at all. Hitting ESC brought up the menu screen, but I could do nothing from there as well.
![Screenshot 2024-03-17 215105](https://github.com/loki79uk/FS22_UniversalAutoload/assets/56035627/b89c3af5-7d39-44bf-9d29-2ea1422d248a)

This is on PC and I have only official DLC's and packs installed with no other downloaded mods.

**Comment by loki79uk** [comment] 2024-03-22 09:11
Hi, sorry for slow reply, I'm pretty busy with IRL stuff.  This is because the bale collection mode was designed for courseplay and I never tested manual loading with that mode.  You don't actually need to use it at all.  If you set `enableRearLoading="true"` and/or `enableSideLoading="true"` in your local settings file for any trailer then you can manually load without using the bale collection mode.

Having said that, this is a bug and I have reproduced it, so I should be able to fix it:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/fe0b3fa7-a074-43a4-b110-7318079fc06f)

**Comment by loki79uk** [comment] 2024-04-01 11:24
Hi, sorry it took me a long time to get around to this, somehow I've been really busy lately.

Please try the latest version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.5.1.1

**Comment by loki79uk** [comment] 2024-06-23 17:38
Closing as fixed.

**Closed by loki79uk** 2024-06-23 17:38 UTC
