### ISSUE TITLE
UA collects bale from autoloader

### ISSUE THREAD

**Issue by FanFSEver** [loki79uk/FS22_UniversalAutoload#76] opened 2022-07-23 16:39 UTC
Came across this bug by accident.

When you try to use UA while trailer is positioned next to an autoloader like the Arcusin FSX 63.72 it will also collect bales from the loader. 

However, UA trailer will not be able to move until bales have been offloaded.

If bales are offloaded from UA trailer and the loader is moved the bales will then move with the loader but at the same orientation where it was offloaded from UA trailer. When trying to unload the loader funny times occurs(loader starts to tumble all over) and a forced application exit is required.

Something similar. Very few people might experience it or come across but thought I will mention it as I am on at the moment.
When you are collecting bales with the Arcusin FSX 63.72 and you are using the Unimog U400 mod or the TLX pickups with a flatbed to pull the loader - UA 'Start loading' stays active on vehicle. When using UA it will load bales that was in the loader even though it might be outside the loading zone. If loader unloaded bales UA will load bales irrespective of where vehicle is. I like using the U400 that is why I came across this problem. Used the TLX to check if it happens with other vehicles as well.

**Comment by loki79uk** [comment] 2022-07-23 18:10
Thanks for finding this one.  That is annoying, because I tested this ages ago and it was fine, so I guess GIANTS may have changed how the Arcusin loads bales.  I'll look into it!

**Comment by FanFSEver** [comment] 2022-07-23 19:27
Hi

I just ran a test with all the in game stackers, round and square as well as the 2 Anderson Giants mods and the Heath SuperChaser QM for Hesston bales.

UA collected bales from all the stackers except the Arcusin MultiPack for small bales. It seems that the stackers are stacking the bales as "real bale" objects and not representatives. Not sure if this is applicable but in the past, previous FS versions you could not jump on or put objects on the stackers - in FS22 you can.

I modded an Arcusin FSX to accept Hesston bales and it was much easier than in FS19. Trying to learn Blender now to get the arm of the stacker to look right.

**Comment by loki79uk** [comment] 2022-07-23 19:45
It could have been an issue all along - I definitely tested that it loaded bales from inside the Arcusin, but can't remember then driving the stacker around which would have reproduced this issue.  I've reproduced it now, so just working on a fix, probably to prevent auto loading when they are in the stacker.

**Comment by loki79uk** [comment] 2022-07-23 20:03
I fugured out the difference at least.  Previously I had checked that you cannot load bales once they are inside the bale stacker (because then they are dynamically mounted), but the difference is that if the bales were detected by UAL before they ware loaded by the Arcusin then they will remain valid to load by UAL.  I'll see if I can find a way to prevent that.

**Comment by loki79uk** [comment] 2022-07-23 20:22
Should be fixed now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.0.0-candidate-005

**Comment by FanFSEver** [comment] 2022-07-23 21:57
Tested. Brilliant. Fixed both issues.

**Closed** 2022-07-23 22:30 UTC
