### ISSUE TITLE
warning in game log. 

### ISSUE THREAD

**Issue by KMullins01** [loki79uk/FS22_UniversalAutoload#35] opened 2022-03-28 02:00 UTC
This should be a simple fix. The dash in the file name throws a warning up in the game log. Not a big deal except for those of us who are OCD about errors and warnings. 

Underline's work though.

And an error for not being able to open an xml file. 

Thanks for the hard work and a great mod.

**Comment by loki79uk** [comment] 2022-03-28 07:33
Do you mean when there is a dash in a mod file?  I don't think this mod has any filenames with dashes in them?  Can you copy and paste the warnings and the error into here please so I can try to reproduce.

**Comment by KMullins01** [comment] 2022-04-17 14:45
Sorry for the long gap in replying. If I change it to remove the -main it works. 

![image](https://user-images.githubusercontent.com/73150569/163719547-98724af2-8d3a-4161-b2ef-4f509e850228.png)

**Comment by KMullins01** [comment] 2022-04-17 23:15
Also, not sure if I should start a new ticket, but will this mod work with enclosed vehicles with only opening rear doors? I'm trying to set it up for a delivery van. I'm not sure what the debug is trying to tell me the problem is. I've just got the pallet sitting on the floor at the back. I do not get the load prompt. 

![image](https://user-images.githubusercontent.com/73150569/163735704-9330fd08-1ede-40c4-9567-3dbd8fd31354.png)

**Comment by loki79uk** [comment] 2022-04-20 21:59
For the first issue, it looks like you have downloaded the git repository, not the actual release.  The release has the correct name, as shown in the screenshot here:

![image](https://user-images.githubusercontent.com/76516343/164331017-cdbe67ae-acac-43c7-8e23-379379d81214.png)


For the second question, it looks like the loading zone is too high. The square floating above the pallet should be on the floor.  Open the vehicle in GE and measure the height of the surface using the method explained in the readme file.

The other issue with installing autoload on vehicles with rear doors, is that there is currently no way to prevent loading when the doors are closed, so it is a bit unrealistic, but it should work otherwise.  I could add another function to do this, similar to the folded/unfolded one, but I have not found any vehicles yet that have inspired me to do it.

**Comment by loki79uk** [comment] 2022-04-23 08:31
I'm closing this for house keeping, but please feel free to contact me on Discord if you need help setting up that vehicle: Loki_79#2864

**Closed by loki79uk** 2022-04-23 08:31 UTC
