### ISSUE TITLE
Platzierbare Fläche

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#193] opened 2023-07-25 10:25 UTC
Hallo,

wäre es möglich eine Platzierbare Fläche zu erstellen, die automatisch Palketten stapelt.

mfg

**Comment by loki79uk** [comment] 2023-07-25 11:37
> would it be possible to create a placeable area that automatically stacks pallets.

Yes, I have been planning to do something like that for a while now, but I want to get UAL totoally completed first.  The new GIANTS object storage made it less needed, but I still plan to do it!

**Comment by acton59** [comment] 2023-07-25 14:19
Danke ,

mir gefiele es Paletten automatisch zu lagern, und per Gabelstabler auszuladen. Was mit dem Giants Objektspeicher nicht geht.

mfg

**Comment by loki79uk** [comment] 2023-07-25 17:55
> I would like to store pallets automatically and unload them with a forklift. Which is not possible with the Giants object storage.

Yes, me too!  I have a few other things that I would like to do first:
- Auto loading onto forklift forks 
- Manual loading of logs into log trailers
- Automatic detection/measurement of item dimensions

But after those, I will extend the mod to include a specialisation for buildings.

**Comment by acton59** [comment] 2023-07-26 08:00
Danke, freue mich drauf

mfg

**Comment by loki79uk** [comment] 2023-08-26 21:04
Closing as not a bug.  This is more of a new mod request, rather than a UAL feature request.  It is on my list though!

**Closed by loki79uk** 2023-08-26 21:04 UTC
