### ISSUE TITLE
How to configure MAN TGX 26.640 Platform from ModHub

### ISSUE THREAD

**Issue by Tharnadar** [loki79uk/FS22_UniversalAutoload#37] opened 2022-03-29 13:53 UTC
Hi guys, I would like to integrate the MAN TGX 26.640 Platform from ModHub (https://farming-simulator.com/mod.php?lang=en&country=it&mod_id=233238&title=fs2022) with this awesome mod I'm using everyday.

I tried first to follow the step in the readme.txt, I put the following code inside the vehicle xml file just aftert the opening <vehicle> tag (...,,\FarmingSimulator22\data\vehicles\man\tgx26640\tgx26640.xml)
````
		<universalAutoLoad>
			<vehicleConfigurations>
				<vehicleConfiguration>
					<loadingArea offset="0.000 1.050 -1.055" width="2.40" height="2.20" length="4.50"/>
				</vehicleConfiguration>
			</vehicleConfigurations>
		</universalAutoLoad>
````
but the vehicle does not use the mod.

Then I tried to edit the SupportedVehicles.xml file of the mod with the following code, but still nothing (the path in configfileName looks good)
````
        <vehicleConfiguration configFileName="data/vehicles/man/tgx26640/tgx26640.xml">
            <loadingArea offset="0 1.205 -1.5" width="2.30" height="2.20" length="5.0"/>
        </vehicleConfiguration>
````

Can you help me to understand what I'm doing wrong?

I really would like to use this king of lorry because I hate the dolly trailer and the only one useful for lorry is too big for my savegame.

**Comment by loki79uk** [comment] 2022-03-29 14:35
Editing the SupportedVehicles.xml for mods should look like:
`<vehicleConfiguration configFileName="FS22_MAN_TGX_26640_Platform/tgx26640.xml">`

The first method should have worked though - it needs to be somewhere inside the <vehicle> tags.  I usually put it immediately after the <tensionBelts> tags.  I'll try it out this evening and let you know how it goes.

**Comment by loki79uk** [comment] 2022-03-29 17:13
That looks from the log like you are using an old version.  It should be:
`2022-03-29 18:07   >> FS22_MAN_TGX_26640_Platform/tgx26640.xml (ALL)`

But it could just be because you have the load aread and offset wrong for that vehicle.  Using the following in SupportedVehicles.xml:
```
        <vehicleConfiguration configFileName="FS22_MAN_TGX_26640_Platform/tgx26640.xml">
            <loadingArea offset="0 1.247 -2.0" width="2.45" height="2.80" length="7.8"/>
        </vehicleConfiguration>
```
It works for me with no changes to the vehicle mod xml:
![image](https://user-images.githubusercontent.com/76516343/160667457-6b368897-721a-46fd-9465-9f296adc01d8.png)

**Comment by loki79uk** [comment] 2022-03-29 17:23
Alternatively, adding this text in `tgx26640.xml` works for me too:

```
	<universalAutoLoad>
		<vehicleConfigurations>
			<vehicleConfiguration>
				<loadingArea offset="0 1.247 -2.0" width="2.45" height="2.80" length="7.8"/>
			</vehicleConfiguration>
		</vehicleConfigurations>
	</universalAutoLoad>
```
Attached file as text because it won't let me upload an xml.
[tgx26640.xml.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/8373676/tgx26640.xml.txt)

**Comment by Tharnadar** [comment] 2022-03-29 17:58
Nope sorry, I've also updated the mod to the latest version but I'm unable to use it with that lorry, of course it works with vanilla vehicles.

I've seen you added also the Mack FLatbed support (https://farming-simulator.com/mod.php?lang=en&country=it&mod_id=229429&title=fs2022) but unfortunately it doesn't work with these too.

Thank you for your support, I'll try to investigate more in the next days

**Comment by loki79uk** [comment] 2022-03-29 18:08
Don't know what else to suggest apart from a mod conflict. Try:

1) Download the latest version of this mod and don't change it.
2) Download the attached file from my last post, rename it by removing the .txt and replace that file in the vehicle mod zip
3) Run a game with only those two mods and buy a new vehicle.  Look in the log immediately after buying the vehicle to see if it is recognised as supported.

If that doesn't work maybe post the whole log file on here?

**Comment by Tharnadar** [comment] 2022-04-01 13:15
Hi mate, sorry for the delay. I did exactly what you asked, but still nothing, this is the log.txt file (https://pastebin.com/ccS64Ywu)

**Comment by loki79uk** [comment] 2022-04-02 22:16
There is something weird going on there, I don't have any of these errors:
`Error: Can't load resource 'store_tgx26640.dds'.`
`Error: Error: Unable to find vehicle type name 'TGX26640' for 'data/vehicles/man/tgx26640/tgx26640.xml'`
`Error loadVehicle: unknown type 'TGX26640' in 'data/vehicles/man/tgx26640/tgx26640.xml'`

Add me on Discord and I'll send you the edited mod file that I'm using.  Loki_79#2864

**Comment by loki79uk** [comment] 2022-04-22 07:58
I couldn't reproduce this.  Closing for house keeping, but please re-open or contact me on Discord if you are still having problems.

**Closed by loki79uk** 2022-04-22 07:58 UTC
