### ISSUE TITLE
Loading Area Full when only half filled.

### ISSUE THREAD

**Issue by luxxxl** [loki79uk/FS22_UniversalAutoload#132] opened 2022-11-28 17:59 UTC
![grafik](https://user-images.githubusercontent.com/119350696/204347802-d08b5159-010e-48ab-9355-492efd520f98.png)
The trailer accepts a few logs but then gives me the error of the loading area is full. I have the newest release and no clue what im doing wrong.
appreciate the help!

**Comment by loki79uk** [comment] 2022-11-28 18:23
How long are the logs you are trying to load?  If they are over 12m that would explain it.  If not try resetting the vehicle, or enable debugging (ctrl-shift-F12), try loading again, and then attach the log file on here.

**Comment by luxxxl** [comment] 2022-11-30 02:26
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/10118802/log.txt)
Here is the log file. The logs are cut to 12m length with the Rottne Harvester. Resetting the Vehicle did fix the Problem.
Appreciate the quick help!

**Comment by Williwillswisse** [comment] 2022-11-30 10:07
Hi, it's the same for me.
I think it has to do with the thickness of the trunks.
Trunks spawned via EDC work very good. Cut trees of different thickness don't.
If I should try something that helps you let me know.
Great Mod :-)

**Comment by loki79uk** [comment] 2022-11-30 11:24
From @luxxxl's log file it looks like UAL is not resetting the layer count properly (it should do this when unloading).  There is a limit of 10 layers for logs, to prevent it loading forever, and it is already at 10 layers when it starts loading (which is probably why the vehicle reset fixes it).

@Williwillswisse may be onto something with the thickness as to how it got to 10 layers in the first place.  I only ever tested with neatly spawned logs using UAL console commands or EDC.

If either of you can zip a savegame file where there problem is happening it would help, but otherwise I'll get the tree harvester out and see if I can reproduce it.

**Comment by Williwillswisse** [comment] 2022-11-30 13:29
![image](https://user-images.githubusercontent.com/47098121/204806863-7457d855-7591-4c9f-b661-1e599866fd60.png)
@loki79uk  this is a Modtrailer where I've inserted the code into the xml:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=227137&title=fs2022

	<universalAutoLoad>
		<vehicleConfigurations>
			<vehicleConfiguration>
				<loadingArea offset="-0.100 1.350 -0.055" width="1.8" height="2.80" length="8.10"/>
				
			</vehicleConfiguration>
		</vehicleConfigurations>
	</universalAutoLoad>

Map Silverrun Forrest.
Do you have a Discord Server too?
[savegame18.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10123584/savegame18.zip)

**Comment by loki79uk** [comment] 2022-11-30 14:57
No Discord server, but you can direct message me: Loki_79#2864

**Comment by Williwillswisse** [comment] 2022-11-30 15:22
Does the savegame help?

p.s. How do I send you a DM in DC without a common server? 🙈(I'm an old man)

**Comment by loki79uk** [comment] 2022-11-30 16:12
> Does the savegame help?

I'm sure it will do!  I'll be at work for a few more hours, I'll try it out this evening.

**Comment by loki79uk** [comment] 2022-11-30 18:15
So in the case of @Williwillswisse's savegame, I think it is just because you have not set `isLogTrailer="true"` for that vehicle (it was commented out above).  If I use the following:
```xml
		<vehicleConfiguration configFileName="FS22_HW80WoodTrailer/hw80.xml">
			<loadingArea offset="-0.100 1.350 -0.055" width="1.8" height="2.80" length="8.10"/>
			<options isLogTrailer="true"/>
		</vehicleConfiguration>
```
then it works:
![image](https://user-images.githubusercontent.com/76516343/204876300-471ddb64-e1af-4aa0-9581-64703ab8bc16.png)

I don't think this is the same problem as in @luxxxl's log file, so I still need to get to the bottom of it.

**Comment by luxxxl** [comment] 2022-11-30 18:51
[savegame2.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10126318/savegame2.zip)
there you go

**Comment by luxxxl** [comment] 2022-11-30 18:59
[savegame2_backup2022-11-28_19-19.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10126412/savegame2_backup2022-11-28_19-19.zip)

**Comment by Williwillswisse** [comment] 2022-11-30 19:07
@loki79uk should this line be the miracle:
<vehicleConfiguration configFileName="FS22_HW80WoodTrailer/hw80.xml">

With option
<options isLogTrailer="true"/>
i had the same issue yesterday.

Now it works :-)
Thanks a lot for your fast help.

**Comment by loki79uk** [comment] 2022-12-01 17:44
The best explanation for this is that a bug in a previous version was not resetting the layer count.  That is why a vehicle reset resolved it.  I can't reproduce it anymore with the any of the latest versions since the latest modhub release (v1.3.0.0 inclusive).  Closing for now, but please re-open or start a new bug if you manage to reproduce it again.

**Closed by loki79uk** 2022-12-01 17:44 UTC
