### ISSUE TITLE
FS22 Autoload

### ISSUE THREAD

**Issue by mp7reeper** [loki79uk/FS22_UniversalAutoload#4] opened 2022-02-22 20:56 UTC
Keybinding Issues with the R and I key with ingame key bindings

**Comment by loki79uk** [comment] 2022-02-22 21:00
Can you elaborate?  Does the same thing happen if you bind the functions to different keys?

**Comment by mp7reeper** [comment] 2022-02-22 22:02
Yes it does the same thing. If you try to refill anything from a silo, production point ect it does nothing. I put in the modDesc for the fill key instead of r I put key_lftshift key_d and it worked fine. I also changed in the modDesc the input binding for I as well the tipping function 


Sent from Yahoo Mail for iPhone


On Tuesday, February 22, 2022, 3:00 PM, Loki_79 ***@***.***> wrote:




Can you elaborate? Does the same thing happen if you bind the functions to different keys?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loki79uk** [comment] 2022-02-22 22:08
Can you confirm that this is with the latest version (update_001), or is it a repeat of issue #1.  You say changing the keybinding in the moddesc works, what about when you change it on the key bindings settings page?

**Comment by mp7reeper** [comment] 2022-02-22 22:15
Tried changing it in the ingame settings did absolutely nothing. That maybe on Giants end tho. They have a lot of bugs to work out.

**Comment by mp7reeper** [comment] 2022-02-22 22:17
I'm also running version 1.0.0.0 of Autoload off of your page here in GitHub.

**Comment by loki79uk** [comment] 2022-02-22 22:20
Try downloading it again, or compare to the latest git version.  I won't
update the version number until it is released to ModHub as it ends up on
the leeching download sites as 20 different versions during development.

**Comment by mp7reeper** [comment] 2022-02-22 22:23
I always get your stuff here. Only trust your scripts from GitHub. I'm a modder myself. I either do my own or use yours. So thank you by the way for all you have done for the farming simulator community and continue to do.

**Comment by loki79uk** [comment] 2022-02-22 22:26
I just mean that v1.0.0.0 in the moddesc does not tell you which version you have.  A similar bug was reported in #1 and #2 and I want to check that you are not using the old version.

**Comment by mp7reeper** [comment] 2022-02-22 22:28
Ok re-downloading it now brb

**Comment by mp7reeper** [comment] 2022-02-22 22:41
All is well my friend. Must have been a bad download for some reason.

**Comment by loki79uk** [comment] 2022-02-22 22:51
Glad to hear it is working.  It just means you originally downloaded it in the hour or so before I updated the beta release.

**Comment by loki79uk** [comment] 2022-02-22 22:54
Duplicate of #1

**Closed** 2022-02-22 22:55 UTC
