### ISSUE TITLE
Loaded trailers cause game to lag

### ISSUE THREAD

**Issue by lordbanastor** [loki79uk/FS22_UniversalAutoload#84] opened 2022-08-14 03:04 UTC
While loaded, any trailer causes lag when speed goes over 35 kph. This issue started after v.1.2.1.1. I tested with vanilla trailer Kröger PWO 24 loaded with cotton bales, as well as various pallets, and with vanilla Krone Profi Liner trailer loaded with various pallets. Also observed with Transportwagen TP 500 S, loaded with pallets. The lag doesn't happen when the trailers are empty.

**Comment by ddewar** [comment] 2022-08-14 14:55
Hey @lordbanastor,

I haven't had much luck reproducing this issue. I tested 2 of your above scenarios and included some screenshots. Please let me know if you are doing something very different from what I have below. 

Any chance of a video of this happening or anything noted in the log? The only issue I had in my log was the usual cotton bale missing CPU mesh that is a base game issue. Another question would be do you have a list of mods installed? Maybe there is some sort of conflict.

![image](https://user-images.githubusercontent.com/15822357/184542319-773b5a83-51a3-4242-a240-ef88d52789e0.png)
![image](https://user-images.githubusercontent.com/15822357/184542524-2056f927-ccec-405e-8763-c6d23aeef171.png)

**Comment by lordbanastor** [comment] 2022-08-14 18:20
I have made a video showing the lag with the mod. Indeed I have some mods loaded with Universal Autoload, but I have testes without most of them, to get the same results. In the video below, I have the following mods loaded to the save game:

Autodrive v.2.0.0.7
Courseplay v.7.1.0.2
Easy Development Controls v.1.2.0.0
Universal Autoload v.1.2.1.1
Vehicle Explorer v.0.2.0.4

I also tested with absolute no mods, and got no lag. Tested with Universal Autoload mod only, and got the same result as the video, so I felt no need to record all over again. Also there is no warning or alert in the log, or something indicating an issue. 

Test video link: https://youtu.be/oEYxi2rGNUU

**Comment by loki79uk** [comment] 2022-08-16 15:10
I tried to reproduce on my machine and got a fluctuating (uncapped) frame rate between 80 and 100 fps, but no obvious difference at high or low speed (apart from new buildings coming into view).  I got very similar frame rates for the same game with no mods at all.

This seems really odd if it only happenes in 1.2.1.1 and not before, since there were only fairly minor changes in that release: https://github.com/loki79uk/FS22_UniversalAutoload/commit/9aaec2d1407f21a19d3dd7fe61b7200e22ff8d48

Can you confirm that it does not happen with 1.2.1.0?
https://github.com/loki79uk/FS22_UniversalAutoload/releases/download/v1.2.1.0-candidate-001/FS22_UniversalAutoload.zip

**Comment by lordbanastor** [comment] 2022-08-18 01:59
I did a round of testing with older versions, from v.1.1.0.0 up to 1.2.1.1 and the problem showed itself from version 1.2.0.0-candidate-002 up. The versions 1.1.0.0 and 1.2.0.0-candidate-001 didn't have the issue. For these tests, I used my current savegame, with all my mods loaded, and the problem only happened on versions newer than 1.2.0.0-candidate-001. I hope this is not a issue exclusive to me. My PC is not a ultra one, but I guess the problem is not my rig. Hope you can solve this. Best regards...

**Comment by loki79uk** [comment] 2022-08-18 10:04
Thanks for the testing that is really helpful.  A lot of things were added in candidate-002, but not much that I think could increase lag.  Can you please try these two versions and see if there is any difference.  You may notice that the F1 menu does not update properly, but don't worry about that.

https://www.dropbox.com/s/kbdrsvac34k76ei/FS22_UniversalAutoload_1001.zip?dl=0
https://www.dropbox.com/s/ypuxy8nwlv2v8s9/FS22_UniversalAutoload_1002.zip?dl=0

**Comment by lordbanastor** [comment] 2022-08-18 11:51
I did the test as you requested, and with v.1001 there was a small lag, like pulses every second, but playable. With v.1002 there was no lag at all, but I noticed the hotkeys were not working properly, specially the ones to control folding/unfolding/loading/unloading (SHIFT+Z/SHIFT+R) outside the vehicle. Other than that, everything worked fine.

**Comment by loki79uk** [comment] 2022-08-18 12:41
Okay, that is great - at least we have identified the cause now.

This seems to be due to my fix/workaround for #58, where rebuilding the F1 menu to show the missing items is causing the lag.  Having run the test version on my machine, I think it is worth about 10 or 20 fps when unrestricted, but that was not noticable for me because it is above the 60fps framerate cap.  I still can't get a difference with low vs high speed driving though.

I will try to think of a way to optimise the menu refresh - maybe to only rebuild if the expected menu items are missing.  Does it make any difference for you in terms of lag if the menu is open or closed?  I don't think it will, and I think that the missing keybindings were not working at all regardless of the menu being visible or hidden.

**Comment by lordbanastor** [comment] 2022-08-18 13:43
I tested with the menu opened, and indeed there were no notable change in the FPS.

**Comment by loki79uk** [comment] 2022-08-18 17:52
@lordbanastor - Are you available to chat on Discord? Loki_79#2864

**Comment by lordbanastor** [comment] 2022-08-18 18:03
Yes, I sent you an invitation. Lord Banastor#2541

**Comment by loki79uk** [comment] 2022-08-22 20:53
Confirmed as fixed via Discord.  Closing.

**Closed by loki79uk** 2022-08-22 20:53 UTC
