### ISSUE TITLE
Fehler auf Server

### ISSUE THREAD

**Issue by Bandesss** [loki79uk/FS22_UniversalAutoload#152] opened 2023-01-26 16:29 UTC
wir haben den fehler mit der aktuellesten Version von Github
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/10511352/log.txt)

**Comment by loki79uk** [comment] 2023-01-28 11:23
Hi, it looks there is maybe a conflict here with FS22_aPalletAutoLoader.  Can you explain more about what happened to cause it?

**Comment by Bandesss** [comment] 2023-01-28 12:13
Sorry einfach nur was laden wollen

**Comment by Bandesss** [comment] 2023-01-28 20:04
Anbei von Heute die log 
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/10528156/log.txt)
Es passiert durch den Mod von gts Easy develop , beim anschalten der superkraft

**Comment by loki79uk** [comment] 2023-01-29 18:31
I have added some extra checks for objects in UAL (and will include them in the next release), but I think that these errors originate from objets created in FS22_aPalletAutoLoader, not from UAL.  Can you please try to reproduce it with only Universal Autoload active, and then again with only FS22_aPalletAutoLoader active?

Most of the stack traces do not mention UAL:
```
2023-01-28 20:44 Warning (script): Unknown entity id 0 for 'object' in method 'getWorldRotation'.
2023-01-28 20:44 LUA call stack:
  =C:/Users/Administrator/Documents/My Games/FarmingSimulator2022/mods/FS22_aPalletAutoLoader/APalletAutoLoader.lua (1761) : getWorldRotation
  =C:/Users/Administrator/Documents/My Games/FarmingSimulator2022/mods/FS22_aPalletAutoLoader/APalletAutoLoader.lua (1826) : unloadAll
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1706) : raiseEvent
  dataS/scripts/network/Server.lua (468) : readUpdateStream
  dataS/scripts/network/ConnectionManager.lua (28) : func
  ```

**Comment by Bandesss** [comment] 2023-01-29 18:51
Es kam beim Entladen

**Comment by loki79uk** [comment] 2023-01-29 19:14
No you don't need both mods, but some vehicle mods are configured themselves to use FS22_aPalletAutoLoader.

For FS22_UniversalAutoload, the configuration is all done by the script mod (not the vehicle mods).  Unless you are using FS22_UniversalAutoloadModhubAddon (or if you have your own custom settings), then it will only be active on the base game trailers and vehicles.

The easiest test is to try with only one mod at a time to see which one is responsible.

**Comment by Bandesss** [comment] 2023-01-29 20:06
Ok, welchen sollen wir dann benutzen?

**Comment by loki79uk** [comment] 2023-02-27 20:04
I have added some lines that should prevent this issue in [this commit](https://github.com/loki79uk/FS22_UniversalAutoload/commit/99261309d8111f0b60769ce9e3f7169747bac340), but I don't think that UAL is the cause.
Closing for now, but please re-open or create a new bug if you have any further issues.

**Closed by loki79uk** 2023-02-27 20:04 UTC
