### ISSUE TITLE
Higher bale stacks

### ISSUE THREAD

**Issue by Ddees1990** [loki79uk/FS22_UniversalAutoload#190] opened 2023-07-21 06:11 UTC
Hi, I've implemented UAL on a small lowloader mod, i'll mainly use it to haul 120cm square bales, i've added more then enough height, yet it won't stack them higher than 5. Which is, as you can imagine, to high when loading large square bales, but it's to low to my taste for the 120cm bales. I've tried changing some parameters but I can't seem to figure it out, could you point me in the right direction please?

**Comment by loki79uk** [comment] 2023-07-25 11:48
There is a max height of 5 for stacking any item - this is mostly due to the bale physics resulting in unstable stacks which tend to stack unevenly or fall over if you go too high.

You can use the disable height limit flag for the vehicle:
`<options disableHeightLimit="true"/>`

or you can edit the code here:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/e20e3295-9c0d-45eb-88f5-0ed640a0a423)

**Comment by loki79uk** [comment] 2023-08-26 21:03
Closing as not a bug.  Please reopen or contact me on Discord if you are still having trouble.

**Closed by loki79uk** 2023-08-26 21:03 UTC
