### ISSUE TITLE
Is it possible to put pallets on the loader?)

### ISSUE THREAD

**Issue by DatiQ** [loki79uk/FS22_UniversalAutoload#189] opened 2023-07-19 10:41 UTC
The question is probably strange, but I wonder if it is possible to put the pallets on the loader in the "ideal" position?
So as not to ride like crazy and poke the forks into the pallet... and then try to unhook it from the forks for another 10 minutes...

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/10097781/d92d8e01-8afd-4a59-8ddf-295e6d3af3ea)

**Comment by loki79uk** [comment] 2023-07-25 11:52
It is my oldest unresolved feature request - I still want to add this one, but my list of jobs is always growing instead of shrinking!
https://github.com/loki79uk/FS22_UniversalAutoload/issues/89

**Comment by loki79uk** [comment] 2023-08-26 21:01
Closing as duplicate of #89

**Closed by loki79uk** 2023-08-26 21:01 UTC
