### ISSUE TITLE
Suggestion for support custom loading area

### ISSUE THREAD

**Issue by KingArthurLV** [loki79uk/FS22_UniversalAutoload#177] opened 2023-05-11 17:45 UTC
Making some support for FS22_UniversalAutoloadModhubAddon come up with one suggestion, which would make more precise and custom specific to each trailer support.
What would You think and would it be possible to add option to add container type for loading area.  For example, bale trailer, is able to load only bales. Low board tipper trailer can load bales and liquid tanks, box trailer just for pallets and so on. All container types are already defined in ContainerTypes.xml.
This would allow us to create very specific and custom made autoload support for each trailers. I believe it would make more pleasant and realistic gameplay for users.

example:

`<vehicleConfiguration configFileName="FS22_Profi_Liner_Flatbed/profiLiner.xml" modHubId="227132">
            <loadingArea offset="0 1.25 0" width="2.40" height="2.50" length="13.0" containerType="EURO_PALLET"/>
            <options enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>`

or

` <vehicleConfiguration configFileName="FS22_JunkkariJ16_J18/j16jl.xml" selectedConfigs="1" modHubId="249628">
            <loadingArea offset="0 0.854 -0.93" width="2.65" height="3.8" length="6.3" containerType="BALE"/>
           <loadingArea offset="0 0.854 -0.93" width="2.65" height="2.6" length="6" containerType="EURO_PALLET"/>
            <options isBaleTrailer="true" enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>`

**Comment by loki79uk** [comment] 2023-05-12 22:15
I did consider somthing like that in early stages of design, but it does add a lot of complexity.  It could certainly be done, but I don't see the benefit.  It would require a lot of extra configuration for a small gain, and while there are fixed categories now, it is possible that more will be added in the future.  I intended for the categories to be dynamic, but the issue is that a language translation is required for each one!

The main principle of UAL is that you define the maximum available space, and then it works out what will fit in the space.  The extra bale height was a concession because bales are much lighter and so can be stacked higher with a similar centre of mass.

To think of it another way, if you could make the width wider for some containers (e.g. pallets) then why would you not make it wider for IBCs, big bags or anything else as well?  Essentially, the defined area should be the maximum available flat area without any clipping, and the two heights are one for bales and another for everything else.

**Comment by loki79uk** [comment] 2024-04-10 09:16
Closing as won't fix, but will consider a feature like this in the UAL for the next FS version.

**Closed** 2024-04-10 09:16 UTC
