### ISSUE TITLE
Not all options showing in F1 Menu

### ISSUE THREAD

**Issue by Camaro2ss** [loki79uk/FS22_UniversalAutoload#58] opened 2022-05-30 23:43 UTC
I am currently using the Brantner DD 24073/2 XXL and all that shows up is Load and unload I cannot see Unload side selected material type or selected material container type. Is there a reason for this I have the most recent version 1.0.5.0 that came out 3 days ago. Thanks for any help. BTW it is a awesome mod extremely helpful I love it.

**Comment by ddewar** [comment] 2022-05-31 00:51
Might have to reset the keybinds. They have been notoriously flakey lately. If that doesn't work might be a mod conflict.

**Comment by loki79uk** [comment] 2022-05-31 08:32
If you can try resetting your keybinds, it would rule that out.  Otherwise can you check your keybindings for any other mods with actions set to those keys?

I know it is never helpful to hear, but it works for me:
![image](https://user-images.githubusercontent.com/76516343/171129247-a1461752-3e2a-4820-8166-a4cdfc70b682.png)
![image](https://user-images.githubusercontent.com/76516343/171129292-0734ffaa-fc92-4339-bd3c-354acd684b87.png)

**Comment by ddewar** [comment] 2022-05-31 14:55
Something else worth noting, is it when in a cab or out of the cab next to the trailer. Sometimes when I backup from a trailer the options show up in the F1 menu.  Not sure why though.

**Comment by RobTomcat** [comment] 2022-06-13 16:28
Just fyi, I have this problem too and with other mods as well not showing all their key choice options.  However, if I just have UA loaded and no other mods, all UA key choices appear.  

I believe Giants somehow prioritise in their opinion what key choices appear in the Hud and this means you don't see all available options.  There is also no way I have found to control what choices or how any choices appear in the list.  Would be very useful for someone to create a mod for this, but I suspect unlikely since it would probably involve internal alterations to  Giant's code.

**Comment by loki79uk** [comment] 2022-06-14 10:42
Could be related to this bug, which depends on mod loading order (so consistent with keybinding registration): https://github.com/loki79uk/FS22_UniversalAutoload/issues/51#issuecomment-1127384233

**Comment by Myiamoto86** [comment] 2022-06-24 04:02
Loki, I had this problem too. This occurred in English and Portuguese BR. But when I get out of the vehicle and go next to the trailer, the other options appear.

**Comment by Yiddan** [comment] 2022-07-11 09:52
Old topic, but as i also have this "no keybinds showing in F1 menu" i figured i could come around and tell how i make them appear:
- I have to get out of the vehicle and come near the trailer
- in menu i dont see keybinds
- i press F1 twice, menu reappears with UAL keybinds.

I hope this can help some to use the mod,
Have a great day everyone ;)

**Comment by loki79uk** [comment] 2022-07-12 21:25
> Old topic, but as i also have this "no keybinds showing in F1 menu" i figured i could come around and tell how i make them appear:

If you are able to reproduce this easily, could you please try renaming the mod zip file to make it load first (i.e. start with A).  I have a suspicion that it could be to do with loading order, but it would be good to prove one way or another.  I still can't reproduce, so that makes it pretty difficult to figure out what is going on!

**Comment by Yiddan** [comment] 2022-07-12 22:42
I'm away from home for a few days. Ill keep the notification unread so i remember to do that verification once im back.
I'll report for sure when done

**Comment by loki79uk** [comment] 2022-07-17 18:41
I made a bit of progress with this, but I still have no idea what is actually going on.  I added a new key binding that was exhibiting this problem of not always showing, even though the debugging text suggested it was enabled.

I 'fixed' it in this case by clearing the whole UAL F1 menu and rebuilding it (instead of just updating the setting that changed).

HOWEVER, when I tried fully refresh the menu instead of each individual key update, then it was actually worse with many of the keys not showing at all.

**Comment by Myiamoto86** [comment] 2022-07-18 07:15
Loki, good morning.

An observation. I've been observing that many other mods are having this problem. I'll try to find out for sure which they are so I can pass you on... This problem may be related to later updates of FS22 itself.

**Comment by loki79uk** [comment] 2022-07-18 08:21
> An observation. I've been observing that many other mods are having this problem. I'll try to find out for sure which they are so I can pass you on... This problem may be related to later updates of FS22 itself.

Thanks, it would be helpful to have another way to reproduce.  I'm at the point now where I can reproduce it for one particular key binding in one particular action sequence (enter already loaded vehicle, then unload it and the new F1 item does not display), even though the debugging line prints to confirm that it should have been updated.  After that, exit and re-enter and it is displayed as expected.

**Comment by Yiddan** [comment] 2022-07-18 10:27
I kinda feel idiotic,
I renamed UAL to FS22_1UniversalAutoload.zip and it seems to no longer work at all ahah
I anybody can point me to the proper renaming procedure i can do the test loki asked about :/

**Comment by RobTomcat** [comment] 2022-07-18 14:20
> I anybody can point me to the proper renaming procedure i can do the test loki asked about :/

See my post above where I tested the issue.  FS22_AUniversalAutoload.zip worked for me.

**Comment by Yiddan** [comment] 2022-07-18 15:05
Oh i didnt notice you renamed the mod.
Thx for your tests ;)

**Comment by loki79uk** [comment] 2022-07-22 15:50
I may have finally solved this..  Please try this release and let me know how it goes:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.0.0-candidate-002

**Comment by Myiamoto86** [comment] 2022-07-22 19:26
![Farming Simulator 22 Screenshot 2022 07 22 - 15 55 58 02](https://user-images.githubusercontent.com/108041428/180505791-10b88859-8332-4f51-911a-07667353c53e.png)

Loki, good afternoon. For now it was a quick test and really managed to make a big breakthrough. The options in the F1 menu are no longer gone, even with VCA active, which was mostly responsible for the problems with your mod. But two options are not working, one of them is automatic bale loading (CTRL+SHIFT+R), which is not showing in the F1 menu and is not working. The other is the loading of square cotton balers, given the error in the attached image. and does not load to any of the trailers that accept the load type.

**Comment by loki79uk** [comment] 2022-07-22 20:42
> Loki, good afternoon. For now it was a quick test and really managed to make a big breakthrough. The options in the F1 menu are no longer gone, even with VCA active, which was mostly responsible for the problems with your mod. But two options are not working, one of them is automatic bale loading (CTRL+SHIFT+R), which is not showing in the F1 menu and is not working. The other is the loading of square cotton balers, given the error in the attached image. and does not load to any of the trailers that accept the load type.

Thanks for testing!  Both of those are expected I think.
1) The new auto-bale loading mode is only enabled on the bale trailers, not for everything.  I would not use the KRONE to drive around a field collecting bales, and the extra menu item is annoying if you will never use it.  You can add it your self though, by copying the config to your local mod settings file and adding `isBaleTrailer="true"` to the options.
2) I'll check, but I'm pretty sure cotton bales don't fit in the KRONE, so the error is just telling you that it won't fit.

**Comment by Myiamoto86** [comment] 2022-07-22 20:47
The cotton bale problem is occurring with all trailers.

**Comment by loki79uk** [comment] 2022-07-22 20:53
> The cotton bale problem is occurring with all trailers.

I was wrong again, it is not alwaysRotate, but this line: `local shouldRotate = ((N2*M2) > (N1*M1)) or (N1 > N2)`
I need to also check for zero values.

**Comment by loki79uk** [comment] 2022-07-22 20:59
Okay, I've fixed the cotton bale, and now the small hand bales tend to stack long ways as well, which I think is okay:
![image](https://user-images.githubusercontent.com/76516343/180567708-5b42e2ec-f057-40d3-b197-e6dbf9810781.png)

**Comment by loki79uk** [comment] 2022-07-22 21:17
Or do you prefer this orientation?  I think it is a bit more efficient when you don't know how many bales of that size will be added.
![image](https://user-images.githubusercontent.com/76516343/180569777-898d1828-ea15-4727-b1c2-f38acc2574c0.png)

**Comment by loki79uk** [comment] 2022-07-22 21:18
Cotton is working for either: 
![image](https://user-images.githubusercontent.com/76516343/180569903-7d57489f-8ce2-4439-93a4-4ecd62780701.png)

**Comment by loki79uk** [comment] 2022-07-22 21:19
I think I'll go with the second loading pattern for small bales:
`local shouldRotate = ((N2*M2) > (N1*M1)) or ((N1>N2) and (N2*M2)>0)`

**Comment by loki79uk** [comment] 2022-07-22 21:27
> The cotton bale problem is occurring with all trailers.

Should be fixed in this one now:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.0.0-candidate-003

**Comment by loki79uk** [comment] 2022-07-23 16:16
So what does everyone think, can I close this issue now?  It seems pretty good for me so far...

**Comment by FanFSEver** [comment] 2022-07-23 16:23
I have noticed that when Autodrive's Display help is activated then UA is pushed out of the help menu.

I like the pop up GUI from Courseplay. Easy to activate and it shows you all your options. But I guess that is a lot of extra coding.

**Comment by loki79uk** [comment] 2022-07-23 21:16
> I have noticed that when Autodrive's Display help is activated then UA is pushed out of the help menu.
> 
> I like the pop up GUI from Courseplay. Easy to activate and it shows you all your options. But I guess that is a lot of extra coding.

When a mod registers a keybinding, you have to set the importance level which dictates the position in the F1 menu.  I make load/unload/etc as GS_PRIO_HIGH, then all the other stuff is either GS_PRIO_NORMAL or GS_PRIO_LOW.  I guess that if AD is pushing stuff off the menu then it is setting all of its keys to NORMAL importance or higher.  Although, once you learn the keys then you don't actually need them on the F1 menu.

**Comment by FanFSEver** [comment] 2022-07-23 22:18
Thank you for the explanation. 

I agree that the more you use a mod and keybindings are involved you don't need them after a while. That being said, when there are certain settings like the type of object or content that can be changed it helps to know what the current selection is. That is why I think the Courseplay developers were smart to go the GUI route. Important info and controls are available at a glance and no need to keep on fighting and changing codes to try and get a higher ranking/listing in the F1-menu.

I have gone from using mostly shortcut key in using Courseplay to only activating the GUI with a mouse combo setting and control Courseplay from there. When I have finished setting the vehicle up and active I close the GUI again with the combo.

As I said that this is just a mention of how a player interacts with mods. And I really enjoy using Universal Autoload.

More experienced users will not have a problem with the current way UA works and might even find it easy but new and inexperienced users might be challenged in using it effectively.

I think you may close this issue now.

**Comment by loki79uk** [comment] 2022-07-23 22:52
Yes, point taken about the filter types, maybe I should give them higher prioritiy - but then it could push other important things off the menu.  I'm sure that I have seen people on YouTube cycle through different pages of the F1 menu, but I have no idea how they did it!!

I would like to make a full GUI like CP, but it is a lot of extra work and I only have limited time for modding.  Originally I even planned a GUI like that to adjust the loading dimensions, but maybe that was a bit too ambitious.

**Closed** 2022-07-24 20:15 UTC

**Comment by awillimd** [comment] 2023-07-17 17:02
I managed to solve this issue for me by setting General Settings>Input Controls>Input Help Mode to "Auto". When I originally had it on "Gamepad" (I'm running FS22 on a PC), the HUD specific to Universal Autoload would not show up correctly. Hope that helps others. Let me know if it works for you.
