### ISSUE TITLE
Not an issue, but a question: Selection of the unloading side

### ISSUE THREAD

**Issue by SchorschiBW** [loki79uk/FS22_UniversalAutoload#51] opened 2022-05-06 20:42 UTC
Will it be possible to select the dumping side?

**Comment by loki79uk** [comment] 2022-05-06 20:52
For ordinary open trailers you can select the unloading side using `U` (default key).  For the KRONE or any trailer configured as a curtain trailer, then you can only unload on the side where the curtain is open.  If you press `shift + F12` the debugging display will show where they will be unloaded:

![image](https://user-images.githubusercontent.com/76516343/167214745-7605d62c-f39e-4507-9f98-49989f685c30.png)

**Comment by SchorschiBW** [comment] 2022-05-06 21:28
Okay, i will try it again.

**Comment by SchorschiBW** [comment] 2022-05-07 15:38
Okay, it works. But i don*t see anything about side selection in the f1 menu

**Comment by loki79uk** [comment] 2022-05-09 15:13
That is strange, do you have other mods running with a lot of other keybindings?  Sometimes there are too many to display all of them.  I saw one of the FS YouTubers cycle through different pages of the F1 menu once, but I have no idea how they did it, or even who it was now..

**Comment by SchorschiBW** [comment] 2022-05-09 17:07
I have Courseplay and AutoDrive, sometimes palletAutoload
![Landwirtschafts-Simulator 22_2022 05 09-19 04](https://user-images.githubusercontent.com/16411797/167461282-dbab5acc-73ed-4bca-903d-0c87b20ecf92.png)

**Comment by loki79uk** [comment] 2022-05-09 17:21
Key bindings in the game seem to be a bit of a mess right now, but I don't know why it wouldn't work.  Do they all show for you if you create a game using UAL only?

**Comment by judg393** [comment] 2022-05-09 18:58
you can turn off the jeybinds for CP in f1 menu @SchorschiBW

**Comment by SchorschiBW** [comment] 2022-05-10 08:40
@judg393 i know but why should i? Other mods have a long list of keyboard shortcuts, all of which are displayed. I don't think courseplay is the problem

@loki79uk During testing I found the following:

When I have the Universal Autoload in, I get the following:

R key: Open object options: <Loading point>

![fsScreen_2022_05_10_10_27_35](https://user-images.githubusercontent.com/16411797/167585920-cd55bcbc-d78b-4a9d-8604-37ed91a0003d.png)

When I press the R key, I see the following

![fsScreen_2022_05_10_10_27_40](https://user-images.githubusercontent.com/16411797/167586062-e381d777-4e56-4263-9c9d-bd4d37b0201f.png)

As a result, I can no longer open the menu in the workshop. So I can no longer sell or configure anything. I can even sell placed objects

![fsScreen_2022_05_10_10_37_12](https://user-images.githubusercontent.com/16411797/167586830-47df0806-173c-4118-b722-58b5986eed0b.png)

**Comment by loki79uk** [comment] 2022-05-10 09:30
I've never seen "open object", but messed up R key bindings reminds me of this bug with Refillable Pallets: https://forum.giants-software.com/viewtopic.php?f=964&t=188578

Can you reproduce it with only UAL installed?

**Comment by SchorschiBW** [comment] 2022-05-10 11:22
I deleted FS22_Fillable_Pallet, but the error still comes up. But only if Universal Autoload is included.
I am now certain that it is due to another mod but it seems to be influenced by Universal Autoload as it works fine without Universal Autoload.
Universal Autoload as such also works perfectly if I only activate this mod and play without any other mods.

It's a mystery. Let's see if I can find out what else mod it could be

**Comment by loki79uk** [comment] 2022-05-10 11:39
It is not just caused by FS22_Fillable_Pallet - but seems to be a base game bug that occurs with any fillable pallets in the game.  FS22_Fillable_Pallet is just a direct edit that makes it so that the base game fillable pallet is purchasable in the shop, there is no other script or change to the base game at all.

Having said that, the fillable pallet bug results in the text something like R = "Refill Pallet", and also is reproducible without any other mods (as long as a pallet is close to a fill source).  So, while it seems similar, I don't think it is exactly the same, but maybe the same root cause.

**Comment by loki79uk** [comment] 2022-05-10 11:49
Actually, it looks like GIANTS have improved things with the latest patch, but not fixed.

With no other mods installed and a refillable pallet near a fill source, the "Refill Pallet" option exists where ever you happen to be on the map:
![image](https://user-images.githubusercontent.com/76516343/167621245-a8c7343c-b7bd-48b5-8ef2-fb00a7ea8689.png)
However, unlike previous versions, the standard R commands (such as sleep, open helpmenu, etc) are now working:
![image](https://user-images.githubusercontent.com/76516343/167621249-8d9061f9-1736-4cf3-827e-42ab3e0c3006.png)

**Comment by loki79uk** [comment] 2022-05-10 11:51
I guess the first clue would be to find the real intended use of the command: "Open Object"

**Comment by SchorschiBW** [comment] 2022-05-10 12:25
Could it be because of the map?

I have now activated all mods on the Elmcreek, I don't have the problem there

**Comment by SchorschiBW** [comment] 2022-05-11 18:08
Short interim status: I once created a save game without any mods and activated my mods alphabetically one after the other. I got as far as precision farming, from there I had the error.
So I thought precision farming might be the problem. But this is not the case:
New save and only activated the scripts (precision farming too) and it works.

Now I'm in the process of activating the other mods one after the other for the scripts. So it may be a while before I find the culprit mod

**Comment by SchorschiBW** [comment] 2022-05-12 09:00
I have now located a subsoiler that appears to be involved in the problem. If I take that out, everything is fine.
Here the question arises: what does the subsoiler have to do with the problem? For me absolutely incomprehensible.
Searched for more mods and got stuck with the mod version of the Disc-O-Vigne, an original machine that only has the working width extended to 3 meters.
If it is activated and I activate another mod, I have the problem again. If I deactivate the other mod, the problem persists. So I have to deactivate the Disc-O-Vigne, start the game and save, then I can activate the Disc-O-Vigne again, but then I am not allowed to activate any more mods, otherwise I have the problem again.
That's too stupid for me, I'll probably play with the problem or just have to do without the universal autoload

Thank you for your suggestions and your help

**Comment by loki79uk** [comment] 2022-05-12 09:22
That sounds like a conflict similar to #42 where the symptoms only occur depending on the alphabetical name order of the loaded mods.  The problem in that case was removing an event listener during the event loop.  So the event array is resized, but not the iterator, and the result is that one of the functions (for the next mod alphabetically) is never called.  This could be a similar thing in another mod (or UAL), but that exact problem should not happen anymore with UAL since I have now commented out all of the 'remove event listener' commands: https://github.com/loki79uk/FS22_UniversalAutoload/commit/6a4a52c6fb9b23993f0bf061f987a3fdba0f0853

**Comment by SchorschiBW** [comment] 2022-05-12 11:54
The problem is, if I now send you the mods I've identified, it won't do much good. The mods in a different constellation can definitely work, such as my first attempt when I suspected precision farming, which in turn has no problems with minimal mod compilation.
I have many mods in the folder, if I sent you all of them it would probably take you 2 weeks to get to the mod that would actually be responsible.
I would say let's leave it at that and let chance decide

**Comment by loki79uk** [comment] 2022-05-12 12:13
One thing that you could try, is use a tool that can search inside zip archives (such as TotalCommander64), and search for the string `removeEventListener` inside your whole mods folder.  It may not find anything, but would rule that out as a possible cause.

**Comment by loki79uk** [comment] 2022-05-12 12:21
Another idea is to rename UAL to something like `FS22_aaaUniversalAutoload` or `FS22_zzzUniversalAutoload` to change the loading order and see if it still happens both times

**Comment by SchorschiBW** [comment] 2022-05-14 19:43
Short test:

FS22_aaaUniversalAutoload doesn't work, but FS22_zzzUniversalAutoload seems to work

**Comment by loki79uk** [comment] 2022-05-15 19:03
I've not seen anything similar to this before.  Could you please send me the log files for both of those?

**Comment by SchorschiBW** [comment] 2022-05-16 08:31
Log with FS22_aaaUniversalAutoload.zip
[log_aaa.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/8698394/log_aaa.txt)

Log with FS22_zzzUniversalAutoload.zip
[log_zzz.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/8698393/log_zzz.txt)

I renamed it again in FS22_autoeUniversalAutoload.zip, so it loads directly after Autodrive. It works and it shows most of the Input Bindings, except the Key U

**Comment by vitalii2011** [comment] 2022-05-21 06:26
> Странно, у вас есть другие моды, работающие с большим количеством других сочетаний клавиш? Иногда их слишком много, чтобы отображать их все. Однажды я видел, как один из ютуберов FS просматривал разные страницы меню F1, но я понятия не имею, как они это сделали, или даже кто это был сейчас.
https://codesandbox.io/s/ef7q5

**Comment by vitalii2011** [comment] 2022-05-21 06:27
> That is strange, do you have other mods running with a lot of other keybindings? Sometimes there are too many to display all of them. I saw one of the FS YouTubers cycle through different pages of the F1 menu once, but I have no idea how they did it, or even who it was now..

https://codesandbox.io/s/ef7q5

**Comment by loki79uk** [comment] 2022-05-31 08:46
Is the unloading side still not correct for you?  I wonder if it could be a mod where the orientation of the trailer is not defined in the usual direction?  It is showing correctly for me:
![image](https://user-images.githubusercontent.com/76516343/171132057-98d1ea9d-3b1b-4547-855c-da498a669550.png)
![image](https://user-images.githubusercontent.com/76516343/171132115-9bb6d632-9cec-4ae5-889c-6f5ecda176c4.png)
![image](https://user-images.githubusercontent.com/76516343/171132167-d84a1857-8262-471e-b4bd-0637c456f841.png)

**Comment by vitalii2011** [comment] 2022-05-31 10:27
> mod where the orientation of the trailer is not defined in the usual direction?
Yes. Literally, yesterday I discovered that the Small Flatbed Trailer https://www.modhub.us/farming-simulator-22-mods/small-flatbed-trailer-v1000 + Universal Autoload Modhub Addon has "the wrong side like everyone else". That is, everything is as it should be with the text in UA. Sorry to bother you.

**Comment by loki79uk** [comment] 2022-06-14 10:44
Closing this, as I think all that is left is now a duplicate of #58

**Closed by loki79uk** 2022-06-14 10:44 UTC
