### ISSUE TITLE
FPS Issues Near UA trailers

### ISSUE THREAD

**Issue by Bovrinox** [loki79uk/FS22_UniversalAutoload#183] opened 2023-06-27 18:36 UTC
hi there, excellent work on this mod, works a treat, and been using it a while. I have noticed however that whenever I am near any vehicle or trailer with universal autoload on it, i get really bad frame rate. It drops right down below 20 fps from 60+ until i move a few meters away again. It doesn't seem to happen if manual only is activated.
Occasionally it starts happening while driving with a few items loaded too, making it impossible to drive. The AI can drive the vehicle just fine as long as I am nowhere near it. 
Anyone else experiencing this problem?

**Comment by loki79uk** [comment] 2023-06-27 19:28
There have been a few people reporting lag issues like this.   I can't find another one on GitHub, although I have at least one thread on Discord.  What is your system spec?  Do you have a lot of bales out on the fields?  I have never managed to reporduce it fully myself.  I can get an FPS drop, but nothing as severe as that.  UAL does do extra calculations on top of the base game stuff, so it could be much more noticeable if your system is CPU bound.

The lag when driving sounds like a bug though.  Either way, can you send me a zipped save game of when it is happening for you?  Ideally one with minimal extra mods required to reporduce the issue.

**Comment by Bovrinox** [comment] 2023-06-27 20:50
I encounter the issue with no bales at all on the map, but a few piles of logs, not sure if it happens with no logs on the map, i shall test that. It happens whether the trailer or vehicles are near any loadable items or not. I do have quite a lot of mods selected, but not usually actually using all that many at once, and no other autoload mods. Not sure if it happens straight away or after an amount of game time.
 I shall have a play around and see if I can find any mod conflicts over the next few days, and create a save with as few mods active as possible! I can probably remove quite a few that I am not using on my Silverrun Forest save.
The driving issue doesn't happen all that often and I have never managed to work out what triggers it!
It is usually my GPU that bottlenecks my pc, I have fiddled about with the graphics settings until I can get a steady 60 FPS.
Ryzen 5 1600
Geforce GTX 1660 TI
16 GB Ram
Samsung 860 EVO SSD

Thanks for a rapid response! I shall do my best to get more details over the next week.

**Comment by Bovrinox** [comment] 2023-07-03 20:07
Im still working out what causes the fps drop issue, it seems to happen at random, whether or not there are other mods active on the save. Some times it does right as soon as you load the game, other times its ok for a while and then slowly starts getting worse and worse whenever you go into the area it will load items from. Very strange.

**Comment by Bovrinox** [comment] 2023-07-05 19:40
This issue seems to stop happening when the vehicle/trailer you are near is full, and cant load any more items. Almost like its detecting the player as a loadable item and it  confuses it or something

**Comment by loki79uk** [comment] 2023-07-05 20:13
Can you find me on Discord (loki_79) and I'll send you a different version to test?

**Comment by Bovrinox** [comment] 2023-07-06 19:07
Just testing that version now, it does appear to have rectified the issue. Nice one!

**Comment by loki79uk** [comment] 2023-07-07 07:36
Okay, thanks for testing!  I did try to reduce the impact of that before by only calling it every 500ms, but maybe best to add an option to disable that feature altogether.  It does mean that some of the "on foot" features will not work.  Also should not be called when driving, I'll add a fix for that too.

**Comment by Vanquish081** [comment] 2023-07-07 11:29
Yes, now work perfectly, no drop the FPS :)

Thanks!!

**Comment by loki79uk** [comment] 2023-07-07 13:25
Okay great - what do you both think about adding an option into the settings file?

So something like `disableUpdateObjects="true"`, and then you just need to change that in your local mod settings file?

**Comment by Bovrinox** [comment] 2023-07-07 19:27
> Okay, thanks for testing! I did try to reduce the impact of that before by only calling it every 500ms, but maybe best to add an option to disable that feature altogether. It does mean that some of the "on foot" features will not work. Also should not be called when driving, I'll add a fix for that too.

No worries! Thanks for taking the time to investigate.

**Comment by Bovrinox** [comment] 2023-07-07 19:30
> Okay great - what do you both think about adding an option into the settings file?
> 
> So something like `disableUpdateObjects="true"`, and then you just need to change that in your local mod settings file?

What effects does having it disabled have? I haven't noticed anything not working like it used to. Having said that, I personally don't think more options is ever really a bad thing! I would say that if its not too difficult to implement then it might be helpful for some players who experience this issue for whatever reason causes it.

**Comment by loki79uk** [comment] 2023-07-07 22:03
Hopefully this will solve the issue sufficiently, without resorting to completely disabling the on-foot loading.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.0.5

Please both give it a try and let me know how it goes.

**Comment by Vanquish081** [comment] 2023-07-08 13:46
> Okay great - what do you both think about adding an option into the settings file?
> 
> So something like `disableUpdateObjects="true"`, and then you just need to change that in your local mod settings file?

This is for file UniversalAutoload.xml in modSettings folder, true?

**Comment by Bovrinox** [comment] 2023-07-08 18:40
> Hopefully this will solve the issue sufficiently, without resorting to completely disabling the on-foot loading. https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.0.5
> 
> Please both give it a try and let me know how it goes.

tested today and yes it seems fine, on foot controls still work. (I didn't know you could do that, so that's nice!) No issues with frame rate drop.

**Comment by loki79uk** [comment] 2023-07-18 15:55
Hopefully this is good enough for now.  I think any further FPS improvements would involve disabling the on-foot commands.

**Comment by loki79uk** [comment] 2023-07-30 11:28
Can any people who were experiencing this issue before (@Bovrinox @Vanquish081) please test if it happens again with this one:
[FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/12209031/FS22_UniversalAutoload.zip)

**Comment by Vanquish081** [comment] 2023-07-31 07:39
Work fine, no drop FPS after create bales in the same 2 fields.

![fsScreen_2023_07_31_09_37_11](https://github.com/loki79uk/FS22_UniversalAutoload/assets/12070061/b63213b7-b34e-4b9f-bc78-5cb3d24aaaeb)

**Comment by Grisu118** [comment] 2023-08-03 18:40
I still have frame drops with the zip form above 🤔 
Not yet tested with an less modded savegame, as it seems to appear after a random amout of playtime, regardless if I do something with ual or not. 

I was able to fix it once, as I loaded a pallet. But was unable to reproduce that :(

**Comment by loki79uk** [comment] 2023-08-08 07:54
> I still have frame drops with the zip form above 🤔 Not yet tested with an less modded savegame, as it seems to appear after a random amout of playtime, regardless if I do something with ual or not.
> 
> I was able to fix it once, as I loaded a pallet. But was unable to reproduce that :(

That is frustrating - I thought I had nailed it when Vanquish said his was still working.

The difference is that the old one only updates the vehicles when on foot every 500ms:
`UniversalAutoload.onFootCheckTime = 500`

If you get time, can you edit the modhub version (line 16) and try different values for `onFootCheckTime` like 50ms, 100ms, 200ms to see when the lag starts to become noticable.

**Comment by loki79uk** [comment] 2023-08-17 20:24
> I have now a value of `5000` The drops are still there, but they seem to appear some seconds when you are near the vehicle, (which makes sense as the code is only executed every 5s) but if you go away from the vehicle, the drops recovers after another 5 seconds.
> 
> -> So the drop is caused by something in this function, but seems unrelated to how often we the code is called 🤔

Do you have a savegame where this is reproducible? If I can reproduce it here, that would really help to find a fix.

**Comment by Grisu118** [comment] 2023-08-17 20:40
I should be able to provide one, will look into it at the weekend.

**Comment by Grisu118** [comment] 2023-08-25 15:02
@loki79uk I have a savegame and the necessary mods here
https://cdn.ls42.ch/fs22/ual_issue_savegame_and_mods.zip

I removed most of the non necessary mods
I'm able to reproduce it when driving some round around the farm. 
As my fps on that map are much better than on my previous savegame, the drop is not always so hard. From 144 fps down to 90-100.

**Comment by loki79uk** [comment] 2023-08-25 15:31
> @loki79uk I have a savegame and the necessary mods here https://cdn.ls42.ch/fs22/ual_issue_savegame_and_mods.zip
> 
> I removed most of the non necessary mods I'm able to reproduce it when driving some round around the farm. As my fps on that map are much better than on my previous savegame, the drop is not always so hard. From 144 fps down to 90-100.

I'll try it out over the weekend.  At the end of the day, it is doing a load of extra calculations about the closest vehicle to the player and raising active on the autoload pallet dection, so it is likely to have some effect on frame rate.

**Comment by CovertJaguar** [comment] 2023-12-01 01:21
I'm currently using 1.4.4.0.

I just want to relate my experiences with this issue, as they are consistent and repeatable, but not necessary previously described in this thread.

While standing next to any UAL vehicle with the Help Window _turned off_, the frame rate slowly, but steadily, declines as time passes. Moving away returns the frame rate to normal. Returning to the vicinity of the vehicle, drops the frame rate back to the previous dropped level. This continues until I've gone from 60 fps to 4 fps, but can take upwards of twenty minutes to be truly noticeable. Tested multiple times.

However, turning _on_ the Help Window while near any UAL vehicle will immediately cause the frame drop to reset to zero and it will stay at 50 fps indefinitely. It will remain this way until I turn _off_ the Help Window again and the fps starts dropping. 

There is a 10 fps drop that seems to be a constant while near a UAL vehicle. This is always present, but isn't a big problem.

It doesn't matter if the Help Window is on or off, in both states I can still interact with the vehicle autoload function.

I peaked at the code, but there is a lot to parse there. My best guess however is some kind of list isn't being cleared and grows over time when the Help Window is closed. But that's just a random guess.

**Comment by Bovrinox** [comment] 2023-12-01 11:35
That's interesting. I have just started playing again after a bit of a
break, and noticed the issue had returned, and seemed worse than it had
been, but it might have been my imagination. I'll test this when I get home
from work, see if its the same for me

**Comment by Gordon-Dry** [comment] 2023-12-01 14:43
A temporary memory leak? How does the RAM usage behave when standing there while the fps drops over the time?

**Comment by loki79uk** [comment] 2023-12-01 16:54
Thanks for all the help, I found and fixed a memory leak!  I'll release a new version soon.

It only happened when displaying the unloading position, so if you were not using that at the time of the low FPS, then there is a different issue.

**Comment by loki79uk** [comment] 2023-12-01 17:28
I have tested this version leaving the player standing by a UAL trailer for a whole hour, with no noticable lag and no increase in memory usage:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.5.0

**Comment by Bovrinox** [comment] 2023-12-02 12:01
So far so good! Been playing about an hour, not experienced any difficulties as of yet, which normally I would have by now. I didn't get the issue exclusively when using the unloading display, in fact I rarely used that. It does appear that you have managed to find and fix the issue though, good work! Hopefully it has fixed it for others too.

**Comment by CovertJaguar** [comment] 2023-12-05 19:34
Been playing with the new version for a couple days. Haven't noticed any significant lag issues near UAL vehicles. You might have got it. 👍

**Comment by loki79uk** [comment] 2024-04-10 18:26
Has anyone had any more issues with this?  Do you think I can close it?..

**Comment by Puddingnase** [comment] 2024-05-07 09:30
Guten Tag zusammen. Ich habe festgestellt, dass es teilweise Mini-Ruckler gibt, sobald ich mich einem Fahrzeug/Trailer mit UAL nähere. Meist, wenn sie leer sind. Teilweise verschwinden die Ruckler mit längerer Spieldauer, teilweise kommen sie wieder zurück. Die FPS fallen teilweise ab. Aber nicht so drastisch wie bei anderen. Erkennt jemand zufällig in der LOG ein Problem? Danke für die Hilfe
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/15233494/log.txt)

**Comment by Szurabura123** [comment] 2024-05-26 08:55
Hi there,

First of all, your a huge player in the modding community, keep up your great work!

Sadly FPS drops appear after some time when standing near the trailer with UAL. They'll go away when you open the F1 menu. I just starterd playing on MP server with my friend so we are going to see how much does it really impact the gameplay. 

Goodluck out there!

**Comment by loki79uk** [comment] 2024-05-26 11:57
@bvnovaes @Szurabura123 - Thanks for the input, it seems that the F1 menu being closed is key to reproducing the issue.  I will try again this weekend.

**Comment by loki79uk** [comment] 2024-05-26 17:15
> Sadly FPS drops appear after some time when standing near the trailer with UAL. They'll go away when you open the F1 menu. I just starterd playing on MP server with my friend so we are going to see how much does it really impact the gameplay.

I still can't reproduce this.  I made a game with only UAL, unlocked frame rate, turned off F1 and waited 15 minutes:
![fsScreen_2024_05_26_17_52_37](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/6bd066eb-1ab6-4c12-9c78-a77593e15766)
![fsScreen_2024_05_26_18_07_13](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/b4ec114e-1d1c-4245-963e-58ab5422bab9)

Sits at around 120fps (frame rate does depend on direction that I'm looking, but it doens't change if I don't move).  I am in the area of the trailer, I should have made a screenshot of that too, but F1 open or closed didn't matter either.  The reason I removed all mods is because I use 'InfoMessageHUD' and I wondered if that was somehow affecting it..

Can you send me a log file, or maybe even a zipped savegame where it is happening for you?  Is it in SP for you or also/only MP?

**Comment by Szurabura123** [comment] 2024-05-27 09:00
@loki79uk I'm actually going to record that happening if that helps. I'll paste yt link here with the video.

It happens in SP and MP but it seems that in MP it doesn't affect other players. What i mean by that is if i have fps drops while being near the trailer, other players don't get any lag. It looks like it's on my side of game only.

**Comment by Szurabura123** [comment] 2024-05-27 09:35
As promised here is yt link: https://youtu.be/ttVMNYwPWgM
What i did before hand was load some lettuce onto the UAL trailer and did some field work. Maybe 15 minutes in it started happening again. 

[savegame3.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/15453897/savegame3.zip)
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/15453915/log.txt)

**Comment by loki79uk** [comment] 2024-05-27 10:23
> As promised here is yt link: https://youtu.be/ttVMNYwPWgM What i did before hand was load some lettuce onto the UAL trailer and I did some field work. I also used better time warp to skip to next day. Maybe 15 minutes in it started happening again.

Thanks for the video.  I think this is actually expected.  Because of the way that the game engine works any in game calculations have to happen between frames, and so directly affect the frame rate.  UAL is constantly measuring the unload positions and also looking to see which vehicle is closest to the player.  I get about a 20fps drop on my machine when standing away or close to the trailer, but usually cap at 60 fps so would never notice:
![fsScreen_2024_05_27_10_45_06](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/76ab2003-cd32-4402-a8f1-43c72b63139c)
![fsScreen_2024_05_27_10_45_12](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/99092e48-7930-4ea4-93c0-57b487c21ae0)
I put the debugging display on to illustrate, and this costs an additional 10fps for me as well, but it is still doing other calculations with or without the debug display active.

The original bug here was a memory leak when the frame rate eventually dropped down to single figures, and hopefully that is now fixed.  I could still add an option to completely disable the on foot options, and that would help a lot as there has to be contant checking to see which vehicle is closest, but there will always be some frame drops whenever any UAL calculations happen (i.e. during loading/unloading especially).

It is weird that you say the F1 menu open improves it for you though.  For me opening the F1 menu lowers the frame rate by a few fps, but I assume that is because UAL is writing entries and text to the menu.

**Comment by Szurabura123** [comment] 2024-05-27 10:36
I'm going to say it is probably something more. Here I am playing uncaped fps. And they are getting halved.
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/170855919/5e3acab4-baa9-4a7a-9535-f509df94504d)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/170855919/7e30085d-9897-404b-bb36-fba9592ae4b4)
It started happening 6 minutes in

**Comment by loki79uk** [comment] 2024-05-27 10:44
I'm out on a dog walk now, but left it running so will see how it is for me
after an hour.  Is there any change in your CPU usage? I.e. no chance it is
thermal throttling or power saving or something?

**Comment by Szurabura123** [comment] 2024-05-27 10:49
Thermal throttling is out of Picture for sure, Windows is quiet new because i wiped my system not that long ago, drivers are good. I can check power saving when i come back with my dog

**Comment by loki79uk** [comment] 2024-05-27 11:43
I can't explain it, but clearly is happening for you.  I just came back to about 10 fps higher than when I left.  It was peaking at 160fps before, and up to 170 fps when I got back (after an hour).  Maybe because it was night time, idk?  That was with the F1 menu closed.  Have you tried with no other mods?  There were a few you had on your save game that I didn't enable:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/165ddf61-845a-4ead-bb15-97689c269072)

**Comment by Szurabura123** [comment] 2024-05-27 11:46
I will get rid of all of them except UAL and comeback with results

**Comment by loki79uk** [comment] 2024-05-27 12:02
> I will get rid of all of them except UAL and comeback with results
> 
> Looks like you are right. One or combination of the mods apparently caused all of this. Or maybe it was the save that caused it. I will try finding mods that cause this. Thank you for your time!

I would suspect the extended light range one, but let me know if you can reproduce it and I'll see if I can figure out the conflict.

**Comment by Szurabura123** [comment] 2024-05-27 12:25
Realistic damage system is my best guess. ONLY with this mod enabled fps drop from 160 to 120 just by attaching the trailer to the tractor. 
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/170855919/b1dab564-c353-4ade-a394-5b90213a7a57)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/170855919/5dd8aced-4ed3-4ca0-8506-020373219111)

**Comment by loki79uk** [comment] 2024-05-27 12:36
Yeah, it could be a combination of any heavy script mods.  UAL raises the trailer active even when not attached to a vehicle, so it would also trigger any mods with "onUpdate" events.  However, if it correctly handles the flags `isActiveForInput`, `isActiveForInputIgnoreSelection` and `isSelected` then it shouldn't cause high overheads.

The F1 menu effect could be related to enhanced vehicle.  That does a lot with action events, updating the HUD and some custom HUD stuff too:  https://github.com/ZhooL/FS22_EnhancedVehicle/blob/main/FS22_EnhancedVehicle.lua

**Comment by loki79uk** [comment] 2024-05-27 12:38
> Realistic damage system is my best guess. ONLY with this mod enabled fps drop from 160 to 120 just by attaching the trailer to the tractor. **By opening the F1 menu everything is normal again**.

Actually, I didn't see this - sounds like it explains everything!

**Comment by Szurabura123** [comment] 2024-05-27 12:41
@loki79uk Should i reach out to the original creator or just disable it for the time being?

**Comment by loki79uk** [comment] 2024-05-27 13:07
> @loki79uk Should i reach out to the original creator or just disable it for the time being?

I'm just looking now to see if I can fix it.

**Comment by Szurabura123** [comment] 2024-05-27 14:18
Actually I am not able to reproduce it on a new save file as well. All i did in the meantime was changing my game to fullscreen

**Comment by loki79uk** [comment] 2024-05-27 14:59
It could be related to number of pallets, not the vehicles.  There is something in RDS that loops over all the pallets in the game.  However, I added a print statement whenever that was called, and couldn't trigger it.  The F1 menu has to be the key.  Is the the same with that savegame and only RDS, not UAL?

**Comment by Szurabura123** [comment] 2024-05-27 15:10
I haven't tested on my main save, that's where i found out about the issue. Only on a new clean save I found that RDS affects UAL or other way around because those were the only activated mods. On both saves however F1 menu clears everything up. It functions as some kind of refresh button that reverts everything back to normal. I was able to recreate it with grain pallets and lettuce so far.

**Comment by EJWiz** [comment] 2024-06-17 04:58
Hello, I've been having the same issue, and have been trying all the things you all have been. I think I have narrowed it down to one of the mods I have installed as well, I do not have the RDS mod. The one I narrowed it down to was "sleep anywhere". Hope this helps you figure something out. Great mod by the way use it all the time. Will update if I have more issues

**Comment by loki79uk** [comment] 2024-06-23 17:52
> Hello, I've been having the same issue, and have been trying all the things you all have been. I think I have narrowed it down to one of the mods I have installed as well, I do not have the RDS mod. The one I narrowed it down to was "sleep anywhere". Hope this helps you figure something out. Great mod by the way use it all the time. Will update if I have more issues

I've tried with Sleep Anywhere, and it didn't make any difference to FPS around trailers.  Did you also have to wait 20 minutes or something to see an effect?

**Comment by EJWiz** [comment] 2024-06-23 20:07
> > Hello, I've been having the same issue, and have been trying all the things you all have been. I think I have narrowed it down to one of the mods I have installed as well, I do not have the RDS mod. The one I narrowed it down to was "sleep anywhere". Hope this helps you figure something out. Great mod by the way use it all the time. Will update if I have more issues
> 
> I've tried with Sleep Anywhere, and it didn't make any difference to FPS around trailers. Did you also have to wait 20 minutes or something to see an effect?

No I was noticing FPS drop withing 5 min of standing near trailer. I've been having issues still but mostly on mod maps. Right now I'm on Elk Mountain Montana by Elk Mountain Modding, other map I notice it on is Deadwood by Poorboy,Bruce's gaming. Will do more testing to see what I come up with. My best guess is bolth maps have a lot of trees and that seems to drop my FPS with no mods.

**Comment by loki79uk** [comment] 2024-06-23 20:11
> No I was noticing FPS drop withing 5 min of standing near trailer. I've been having issues still but mostly on mod maps. Right now I'm on Elk Mountain Montana by Elk Mountain Modding, other map I notice it on is Deadwood by Poorboy,Bruce's gaming. Will do more testing to see what I come up with. My best guess is bolth maps have a lot of trees and that seems to drop my FPS with no mods.

Have you typically got the F1 menu open or closed?  The only thing that Sleep Anywhere does is spam the F1 menu with some static text, so if it really is that it could be a big clue.  This is literally the entire mod:
```lua
function SleepAnywhere:update(dt)
    if g_currentMission.controlPlayer then
        g_currentMission:addExtraPrintText(g_i18n:getText("SLEEP_ANYWHERE"))
        if Input.isKeyPressed(Input.KEY_lshift) and Input.isKeyPressed(Input.KEY_z) then
            g_sleepManager:showDialog()
        end
    end
end
```

**Comment by EJWiz** [comment] 2024-06-23 20:24
> > No I was noticing FPS drop withing 5 min of standing near trailer. I've been having issues still but mostly on mod maps. Right now I'm on Elk Mountain Montana by Elk Mountain Modding, other map I notice it on is Deadwood by Poorboy,Bruce's gaming. Will do more testing to see what I come up with. My best guess is bolth maps have a lot of trees and that seems to drop my FPS with no mods.
> 
> Have you typically got the F1 menu open or closed? The only thing that Sleep Anywhere does is spam the F1 menu with some static text, so if it really is that it could be a big clue. This is literally the entire mod:
> 
> ```lua
> function SleepAnywhere:update(dt)
>     if g_currentMission.controlPlayer then
>         g_currentMission:addExtraPrintText(g_i18n:getText("SLEEP_ANYWHERE"))
>         if Input.isKeyPressed(Input.KEY_lshift) and Input.isKeyPressed(Input.KEY_z) then
>             g_sleepManager:showDialog()
>         end
>     end
> end
> ```

Closed, if I open and close it, it resets my FPS back to 60 then with it closed it will start dropping again. Let me try with it just open. Also I will get a list of my mods for you.

**Comment by shortcircuit412** [comment] 2024-06-30 16:13
Hey there! 
I'm also experiencing UAL-related heavy frame drops only as a player standing next to trailers / trucks with UAL in manual only mode.
drops from ~60 to 15 fps while in proximity to loading area. 
UAL off = no drops. Sometimes **days** with no drops - sometimes 5min after start. SP/MP both.
May be something related to tabbing between vehicles. Happens after jumping in & out and tabbing quickly.

**Comment by EJWiz** [comment] 2024-06-30 16:58
I also noticed severe drops last night while tabbing between my truck and trailer bolth with UAL, the faster I tabbed the worse it got. With and without the f1 menu open. Agree that it happens worse at times than others. Also I had drops while hauling a big bag of oats in the lizard truck while going over 60mph the other day.

**Comment by loki79uk** [comment] 2024-06-30 18:53
@shortcircuit412 @EJWiz 

Can you both please send me your log files next time it happens?  Easiest on Discord: loki_79

**Comment by EJWiz** [comment] 2024-07-01 04:34
[log UAL.txt](https://github.com/user-attachments/files/16047933/log.UAL.txt)

**Comment by EJWiz** [comment] 2024-07-01 04:42
https://github.com/loki79uk/FS22_UniversalAutoload/assets/173024557/a34fd0ec-165d-4157-98d3-3f2c83ea1b56

FPS dropping while tabbing trailer/truck. log from this clip
[log UAL.txt](https://github.com/user-attachments/files/16047977/log.UAL.txt)

**Comment by loki79uk** [comment] 2024-07-01 06:22
> FPS dropping while tabbing trailer/truck. log from this clip [log UAL.txt](https://github.com/user-attachments/files/16047977/log.UAL.txt)

Thank for that - I read tabbing as actually alt-tab between vehicles, so would never have tried cycling the selected attached vehicle.  I'll try that this evening.

So are you typically getting drops from 58/59 to 40/45 fps?  Have you tried with the minimum required mods, so just using that truck, that trailer and with only UAL active?

**Comment by EJWiz** [comment] 2024-07-01 21:52
On Elm creek doing testing I have found, you get frame drop while cycling vehicle/tool with or without UAL. With UAL it gets severe, every vehicle tool I tried had this affect, even those with no loading ability. After trying a process of elimination all I have come up with is the more mods loaded, the worse it gets. Having something loaded makes it happen faster. Also FPS drop is the worst while driving and the loaded vehicle is selected, FPS goes back up when empty trailer/tool is selected.

**Comment by loki79uk** [comment] 2024-07-01 22:23
> On Elm creek doing testing I have found, you get frame drop while cycling vehicle/tool with or without UAL. With UAL it gets severe, every vehicle tool I tried had this affect, even those with no loading ability. After trying a process of elimination all I have come up with is the more mods loaded, the worse it gets. Having something loaded makes it happen faster. Also FPS drop is the worst while driving and the loaded vehicle is selected, FPS goes back up when empty trailer/tool is selected.

That sounds plausible to me - the menus are updated for every different vehicle or tool selected and I'm sure there are other base game calculations going on as well.  For UAL it certainly does a bit of work all the time that a vehicle is selected, to check that pallets are on board, where they could unload, and also sometimes to force the position update (otherwise in multiplayer the pallets appear not to move at all).  I'm sure there are some optimisations that I could make, but it is quite hard to determine where the savings could be made without a noticable lag in the responsiveness of e.g. loading/unloading buttons being enabled/disabled.

**Comment by EJWiz** [comment] 2024-07-02 02:57
> > On Elm creek doing testing I have found, you get frame drop while cycling vehicle/tool with or without UAL. With UAL it gets severe, every vehicle tool I tried had this affect, even those with no loading ability. After trying a process of elimination all I have come up with is the more mods loaded, the worse it gets. Having something loaded makes it happen faster. Also FPS drop is the worst while driving and the loaded vehicle is selected, FPS goes back up when empty trailer/tool is selected.
> 
> That sounds plausible to me - the menus are updated for every different vehicle or tool selected and I'm sure there are other base game calculations going on as well. For UAL it certainly does a bit of work all the time that a vehicle is selected, to check that pallets are on board, where they could unload, and also sometimes to force the position update (otherwise in multiplayer the pallets appear not to move at all). I'm sure there are some optimisations that I could make, but it is quite hard to determine where the savings could be made without a noticable lag in the responsiveness of e.g. loading/unloading buttons being enabled/disabled.

 Sounds good to me, I really only notice it on certain maps and now that I know what is causing it I can just do things different and have less issue.    Thanks alot for your responsiveness to messages and trying to resolve this issue. Hope you keep up the good work @loki79uk If you would like more info from me, I can do so.

**Comment by loki79uk** [comment] 2024-07-02 06:46
Thanks to everyone who contributed to this issue!

I'm going to finally CLOSE this one as the original issue is fixed (memory leak), and this thread is getting too long to keep track of all the different replies!  I think that any remaining low FPS issues could be improved by some result caching or optimisation, but only an issue in certain situations.

If anyone can provide an example of extreme FPS changes, then please create a new issue (refer to this one if you like) and provide a logfile, or preferably a savegame to reproduce it with minimal other mods and I will do my best to fix it.

**Closed by loki79uk** 2024-07-02 06:46 UTC

**Comment by Vanquish081** [comment] 2024-11-09 13:31
Well... after a few months I started playing again and it's happening again, with the latest version.
If I have to say that it's not as drastic as the first time, it stays at about 20-30 FPS, it's playable, but it's noticeable. Then you get out of the detection zone and the FPS goes up again.
