### ISSUE TITLE
Autoloader leaves Bale gaps

### ISSUE THREAD

**Issue by RobTomcat** [loki79uk/FS22_UniversalAutoload#11] opened 2022-02-25 08:41 UTC
An excellent mod, thank you Loki.

A minor point and not sure if this is deliberate or a small glitch.  Using the Farmtech DPW 1800 bale trailer and square 220cm bales loading them as bales, your mod loads them as either 6-gap-6 or 4-gap-8 (going 2 high) making a 12 bale load. Not sure why the difference in the loading pattern. However, after loosening the straps I can always manually load/squeeze 2 more bales (going 2 high) in those gaps.  So I think this trailer should load 14 x 220cm bales.  There is also always a small unused space at the rear of the trailer - not big enough for a bale - so I definitely think 14 bales is a practical load on this trailer.

**Comment by loki79uk** [comment] 2022-02-25 09:14
I'll have a look at the dimensions.  It is always dynamically calculated, so actually defining the bales as slightly larger can improve packing if it prevents occasional collisions due to slight variations in placement position.  It also may be possible to increase the load area slightly without collisions on the frame.  If you can experiment/edit them yourself and let me know what works best I'll change it in the next release.

**Comment by RobTomcat** [comment] 2022-02-25 20:18
Have tried adjusting the length of the loader in SupportedVehicles.xml.  Tried everything is small increments from 8.0 to 11.0 without success.  Always there is a large gap somewhere on the trailer and sometimes the bales only go 1 high in one place.  Also tried increasing the bale size very slightly, but only had 11 bales loaded as 1 row was again 1 bale high.

Without knowing how you calculate where to place the bales I cannot go further as I cannot beat your 12 bale 'limit' although there is clearly space for 14 x 220cm bales on this trailer.

As I said initially, not a serious problem, just a small irritation I can live with in an excellent mod!

**Comment by NOLA-CML** [comment] 2022-02-25 20:52
@RobTomcat 
Any chance you have any other mods that could be conflicting? Unless I'm using different bales, mine stack 7x2. I came across this thread while trying to figure out what could be causing my issue with bread and decided to test on the silage bales I have.

![20220225145037_1](https://user-images.githubusercontent.com/10129300/155801076-8aefca64-a84a-445a-805f-e1127f9121d4.jpg)

**Comment by RobTomcat** [comment] 2022-02-25 21:22
Interesting and thanks!  I just tried with only the UniversalAutoload in my mod folder, so no other mods and I could only load 10 bales this time!  Are you sure you are using 220cm bales?  

The only other thing which I will try tomorrow is I have the front and back extensions on my DPW 1800 and I notice you do not in your pic.  I would not have thought this would cause an issue but I will try just in case.

**Comment by NOLA-CML** [comment] 2022-02-25 21:23
I can load it up and try. Are you loading silage bales?

**Comment by NOLA-CML** [comment] 2022-02-25 21:57
Even with the extensions, grass and wrapped silage, I can fit 14 bales. Are running on a server by chance?

**Comment by loki79uk** [comment] 2022-02-25 22:28
@NOLA-CML Hi - the bread issue was a mistake on my part. I had set the height too short, it should be:
`<objectType name="bakeryBoxPallet" sizeY="0.920"/>`

You can change it in `ContainerTypes.xml` if you like, but I should have a new version out pretty soon, with a few other fixes as well.

**Comment by loki79uk** [comment] 2022-02-25 22:29
@RobTomcat I've been away for the week on holiday, but back now.  Maybe easier to sort your problem out via Discord?  Loki_79#2864

**Comment by RobTomcat** [comment] 2022-02-26 10:34
@NOLA-CML   My Bales are 220cm Hay, not Silage.   Single Steam PC user, no server.

@loki79uk  Have just redownloaded UniversalAutoload mod and tried again.  No other mods present and I have cleared out my modSettings folder too. 

With the front and back extensions on the trailer I now get 10 bales loaded usually but not always.  Taking the extensions off I get the same result - see pics. What surprises me is that the loading does not always give the same result in the position of the bales loaded - see pics with trailer extension.  In each pic no further bales can be loaded.  Will contact you on Discord this afternoon (if you are around) as you suggest.
![Base Trailer 10 Bales](https://user-images.githubusercontent.com/99221276/155839930-5ed0bcb3-31ba-4d48-96ac-70b8949eb7a3.jpg)
![Extended Trailer 10 Bales 1](https://user-images.githubusercontent.com/99221276/155839944-2c7b7351-0706-403d-aa0e-9dc5a14a74d4.jpg)
![Extended Trailer 10 Bales 2](https://user-images.githubusercontent.com/99221276/155839945-7eb3b227-877a-4494-b066-ed7d3bfb9b14.jpg)
.

**Comment by RobTomcat** [comment] 2022-02-26 13:10
Further update.

I went to the shop and bought Hay bales.  8 at a time x 2 = 16.  Not sure what size they are.  Pulled alongside them and 14 (7 x 2) loaded onto the trailer!

That gave me an idea.  Went back to my field, autoloaded 10 hay bales (again only 10 from random collection) on the trailer, unloaded them in one spot.  Retrieved a few more bales from elsewhere in the field with my front loader and stacked them next to my unloaded 10 bales.  Autoloaded the trailer and all 14 bales loaded!!

Thus the problem seems to come from when you are collecting bales individually in the field.  They can be loaded as 10, 11, 12 bales maximum on the trailer - I have had all variants.  But if all the bales are all together in the field, or at the shop, then you can get all 14 to load correctly.

**Comment by loki79uk** [comment] 2022-02-26 13:49
I think the issue here is due to the trailer moving when loading.  Bales were a recent addition and it was only ever tested for loading when static.  I think that some of the positions calcualted prior to loading have moved by the time the loading takes place - I'll look into it.

**Comment by loki79uk** [comment] 2022-02-28 14:03
I've been thinking that a temporary fix for this would be to prevent loading while the trailer is moving (either disable the button or add a warning message).  Then I can get the current version out onto ModHub without too much delay, and I will have more time to add a 'work mode' for collecting bales for a future update.

**Comment by RobTomcat** [comment] 2022-02-28 14:44
Thanks for the update.  I have no problem with your temporary fix to get a new version released and can accept I will not get a full load when collecting bales from a field.

Just a point though.  The trailer is not "moving" as such when I pick up the bales in the field, it is stationary when I press the "R" key.  But if you mean the trailer is roving the field to collect the bales, then yes, that is true.

**Comment by loki79uk** [comment] 2022-02-28 15:01
I think I misunderstood in that case.  There should not be any gaps between objects if you load when stationary, even if moving in between.  The exception being if you did not strap them, because then the objects can slide and are no longer in the expected positions.

**Comment by RobTomcat** [comment] 2022-02-28 15:07
You can see from the pics I posted earlier the gaps in the loading and the differences between some of the loads.  In all cases the tractor and trailer were stationary when I tried to load the bales.  Apologies if there has been a misunderstanding but I never said the trailer was moving when trying to load the bales.

**Comment by RobTomcat** [comment] 2022-02-28 15:10
If you like I can send you the save file which I have been using for the test.

**Comment by RobTomcat** [comment] 2022-02-28 15:12
ok, let me know when you are live on Discord.

**Comment by loki79uk** [comment] 2022-02-28 17:03
No need to be embarrassed at all.  It may even be an easy fix to load while moving, but if it is not then I'd rather get it released to ModHub in the current state, and then continue to work on new features.

I think the problem is either that the calculations take too long and so everything has moved slightly by the time the loading takes place, or it is because I'm using the wrong coordinate transformations for the situation e.g. local-to-world, etc.

**Comment by loki79uk** [comment] 2022-02-28 23:48
The good news is that I've identified the issue, and can now load bales when moving without any gaps.  The probelm was from the time taken to calculate if the position was occupied or not.  So from an empty trailer it is easy, because that step can be skipped.

Once you start partially unloading and loading again it becomes more complicated, as those steps are required to find the empty spaces when loading new pallets.  I'm going to sleep on it and think about ways to minimise the amount of checking required, but I'm pretty confident that I'll find something that will work.

**Comment by RobTomcat** [comment] 2022-03-01 08:17
That's great news!  Look forward to your next release.

**Comment by loki79uk** [comment] 2022-03-01 22:16
This should be fixed now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-010

Bales can be loaded while moving, as long as the trailer was originaly empty when you started loading.  For all other objects, the trailer must be completely stationary to load.  There is a warning message to let you know when movement is preventing you from loading.

**Comment by RobTomcat** [comment] 2022-03-02 10:01
Perfect!  

After 1 successful run of 14 bales I changed the height parameter of the DPW 1800 trailer to 3.30 from your 2.20 (perfectly reasonable to have the bales stacked 3 high on that trailer I think especially with the front and rear extensions) and loaded 21 bales at quite a speed.  No hiccups!

Many thanks for this excellent mod.

**Comment by loki79uk** [comment] 2022-03-02 10:32
Excellent news!  I did think about increasing the height, the problem is if you go too high with heavy pallets then it is very easy to tip the trailer over on corners.  Also, with the small bales the stacks become very precarious.  Maybe I should make the height user adjustable, or for the open trailers at least the max height could depend on the object size and weight maybe..

**Comment by loki79uk** [comment] 2022-03-02 10:38
I also meant to explain the issue now I understand it better.  The problem seems to be that there is no game function to add an acceleration to an object (maybe there is, but I can't find it).  This means that to load an object, you set the position and the velocity, but it has no acceleration. So essentially if you load at a perfectly constant speed then it is fine, but if the trailer is accelerating, there is a shift in position while a force is applied to the object (via friction) to accelerate the object to match the trailer.

I guess this is why bales are worse than pallets, since they have different mass, friction coefficients, etc.  If you look with debug on, the objects still load into the wrong positions when loaded under acceleration, but the positions shift together, so there is no obvious collision.  Bales seem better than pallets at re-arranging themselves if they overlap each other as well.

**Comment by RobTomcat** [comment] 2022-03-02 13:28
Thanks for the explanations,

I agree with you small trailers stacked too high are very easy to tip over, especially using pallets.  For the DPW 1800 bailer trailer I felt it was large enough to go three high on bales since it is quite a large trailer and also has front and rear axles so is a little more stable than single axle trailers.  On smaller trailers I am not so sure I would want to go that high.  Certainly an option to specify the height of goods on a trailer would be nice, but not a necessity.

Regarding acceleration, I will remember not to accelerate when picking up bales!  

Thanks again.  Rob

**Closed** 2022-03-02 14:20 UTC
