### ISSUE TITLE
UA Addon 20Ft Gooseneck Trailer unload problem

### ISSUE THREAD

**Issue by Winstonsthlm** [loki79uk/FS22_UniversalAutoload#158] opened 2023-02-12 01:42 UTC
20Ft Gooseneck Trailer from Universal Unload Addon will not accept unload key input when inside the vehicle but it works outside.
Changing the key bind for UA it still show "Unload here" as "shift + i" inside vehicle why my guess is that the trailer have an option to dump on ground which is overriding UA action.

It's very odd that the trailer would have that option since it's a flat bed/low loader.

**Comment by loki79uk** [comment] 2023-02-27 19:36
Hi, sorry I've been away for the last couple of weeks.  I see you have also reported this on the Add-on issues page.  Have you made any progress figuring out the cause?

**Comment by loki79uk** [comment] 2023-03-06 22:03
Closing as pretty sure this is an issue with the mod not UAL.  Please reopen if needed.

**Closed by loki79uk** 2023-03-06 22:03 UTC
