### ISSUE TITLE
Manually load stack of pallets

### ISSUE THREAD

**Issue by harokyang** [loki79uk/FS22_UniversalAutoload#232] opened 2024-06-14 06:48 UTC
Whenever I use a front loader fork to pick up stacked pallets and move it to a manual load trailer
Only the very bottom pallet will be recognized and auto loaded onto the trailer
The rest of the stack won't be loaded. They just fall to the fork because the bottom one has been 'stolen'
Have to put the stack on ground and lift it with fork again so the next bottom one can be loaded

This makes loading already stacked pallets pointless, you still have to load them one at a time

**Comment by loki79uk** [comment] 2024-06-14 07:19
This has been a problem ever since the start.  The way that UAL detects a forklift pallet is from the mount attachment.  Only the bottom pallet has a mount attachment, so the top one could be anywhere.

I have a work in progress for a trigger that would be added above the forks to detect all pallets, but I've only got as far as adding the trigger and there are some issues around defining the size and shape vs the forks.  The risk is that it grabs the pallets next to, or below the one you want, etc..  It is not s simple problem.

Another idea I had was to modify the pallets so that they attach to each other, but then what if you want to separate them.

If you have any thoughts for how it could work, I'm open to ideas!

**Comment by loki79uk** [comment] 2024-06-14 07:22
This is pretty much a duplicate of #89

**Comment by harokyang** [comment] 2024-06-14 08:39
So is there a lift fork mod to mount multiple pallets?
Just like what the Bale King did in vanilla game to mount multiple stacked bales

**Comment by loki79uk** [comment] 2024-06-14 08:55
I don't know of any mod like that.  That is essentially what I am suggesting to create, but I don't have enough time to invest in that currently.  If you can find one, I'm sure then I would be able to load them as a stack.

**Comment by harokyang** [comment] 2024-06-14 09:04
I tried some bale grab mods, but UAL can detect none of the bale the mod grab mounted
The Lizard VGrab from Straw Harvest Pack
The Lizard Pro Bale from Pro Bale Grab Autoload

**Comment by loki79uk** [comment] 2024-06-14 09:11
It could be because a lot of these kind of mods actually remove the bales from physics and then it is just a visual representation.  Anyway, I'm not saying that a mod like this will work out of the box, just less work for me if part of the work is already done.

**Comment by harokyang** [comment] 2024-06-14 12:06
Is it possible to put this manual loading switch into game setting menu?

**Comment by loki79uk** [comment] 2024-06-14 13:21
Yes, I have plans to put all settings into a game settings menu, but it is very time consuming.  I did it for Lumberjack recently, but it is much more complex for UAL since there are global settings and per-vehicle settings.  I would like to do it, but I would like to do a lot of thngs and unfortunaly I do not have unlimited time.

**Comment by loki79uk** [comment] 2024-06-23 17:30
Closing as a duplicate of https://github.com/loki79uk/FS22_UniversalAutoload/issues/89

**Closed by loki79uk** 2024-06-23 17:30 UTC
