### ISSUE TITLE
Automatic Bale collection keeps dissapearing

### ISSUE THREAD

**Issue by MiranoVerhoef** [loki79uk/FS22_UniversalAutoload#229] opened 2024-06-10 20:42 UTC
Hello,

I am running your latest version of the mod (1.5.1.0) and I'm running into the issue where my option “Automatic Bale Collection” keeps disappearing on my menu.

Is this a bug since a recent version, perhaps?

This link shows the disappearing (you can see in the F1 menu on the left)
https://youtu.be/sMN_rksKsdc

**Comment by loki79uk** [comment] 2024-06-10 21:04
Can you zip your save game in a position where this is happening please?  You can send it on here or find me on discord - loki_79

**Comment by MiranoVerhoef** [comment] 2024-06-10 21:14
Just added you on Steam. Let me backup the file from the server :)

**Comment by MiranoVerhoef** [comment] 2024-06-10 21:25
Update: Requested files send through Discord. Awaiting result.

**Comment by loki79uk** [comment] 2024-06-11 19:40
I messaged you on Discord, but maybe you don't check it very often so sending here too.  There are some issues with how that trailer is configured.  You can see that the loading zone is too low, it is not really centred, and it is also flipped from front to back so that the rear loading trigger is in the wrong place:
![Untitled](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/475a25c2-1348-4a30-b181-f3a7d0a8a599)

**Comment by loki79uk** [comment] 2024-06-23 17:36
I think we decided that this was an issue caused by too many script mods and/or too many mods that create additional menu items.  Closing as not a bug, but please re-open if you can reproduce consistently.

**Closed by loki79uk** 2024-06-23 17:36 UTC
