### ISSUE TITLE
Manual loading with (mod) container types does not work in MP (Hof Bergmann)

### ISSUE THREAD

**Issue by FReaXit** [loki79uk/FS22_UniversalAutoload#222] opened 2024-03-02 11:46 UTC
I am messing around with a strange / special problem:
I want to play MP (no Dedi) with manualloading (manualLoadingOnly="true" set on server in the modsettings folder). 
With standard vehicles and containers, it is working fine, both on server an client. 

Now I have added containers for HofBergmann map to ContainerTypes.xml in UniversalAutoload.zip
Example:
 <containerConfiguration name="FS22_HofBergmann:onionSack" containerType="ALL" sizeX="0.90" sizeY="0.24" sizeZ="0.58"/>

Result:
Working on server, not working on client. The standard containers still work. Also, unloading of the mod containers work on server an client. 
If i deactivate manual loading (manualLoadingOnly="false" set on server in the modsettings folder), the mod containers are loaded, both on server and client. It is only the manual loading with mod containers which does not work.

I also found several "Universal Autoload Disabled" entries in the clients logfile. Can this be something? 

Thank you very much in advance for helping me.
[logCLIENT.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14469163/logCLIENT.txt)
[logSERVER.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14469164/logSERVER.txt)

**Comment by FReaXit** [comment] 2024-03-02 12:54
Example:
containerConfiguration name="FS22_HofBergmann:onionSack" containerType="ALL" sizeX="0.90" sizeY="0.24" sizeZ="0.58"/

I also tried to put the containerConfiguration into the UniversalAutoload.xml in the modSettings folder.
Same result, manualLoading working on the server but not on the client.

**Comment by loki79uk** [comment] 2024-03-02 17:47
Do you always get these errors?
```
dataS/scripts/FSBaseMission.lua(2850) : attempt to index local 'farm' (a nil value)
dataS/scripts/gui/InGameMenuMapFrame.lua(514) : attempt to index field 'mapOverlayGenerator' (a nil value)
```

You shouldn't edit the UAL zip, just use the mod settings file on the server.  BUT that is not the issue, only that othewise everyone has to update to your modded version.

It is hard for me to repoduce player hosted games, but it really should be the same as on dedi.  Have you tried to reproduce with a dedi host?

**Comment by FReaXit** [comment] 2024-03-03 09:01
No, the game on the client side crashed when exiting the game. Usually that does'nt happen. I have uploaded a log when it didn't. [logCLIENT2.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14472262/logCLIENT2.txt)

As I already mentioned in post 2 I tried without manipulating the UAL zip. I now only use the mod settings file on the server. But like you already said, this wasn't the error as it is stll the same behaviour.

Dedi: For now, I do not have a possibility to try.

I will try to clean up the mod folder and try to run without the other mods (except Hof Bergmann) to exclude any effects that might be caused by other mods.

**Comment by loki79uk** [comment] 2024-03-03 09:20
You can start a dedicated server with the Steam or GIANTS version. There is
a different exe in the main install folder.

**Comment by FReaXit** [comment] 2024-03-03 10:07
I am using the XBox Game Pass Version, so there is no dedicatedserver.exe / license to run a dedi.
Currently testing without the other mods, but i am not optimistic.

**Comment by FReaXit** [comment] 2024-03-03 10:24
Not successful.
I have used only HofBergmann mod + the mods that come with it (see logfile), and a new savegame.

SERVER: 
[logSERVER3.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14472551/logSERVER3.txt)
Standard Hay Bale (manual) load to in-game trailer (Welger DK 115) WORKS
Standard Hay Bale (manual) load to custom trailer (LSFM Güter Transportwagen / transportCart.xml) WORKS
Mod Container (catFoodPallet) (manual) load to in-game trailer (Welger DK 115) WORKS
Mod Container (catFoodPallet) (manual) load to custom trailer (LSFM Güter Transportwagen / transportCart.xml) WORKS

Unloading works with all combinations.


CLIENT:
[logCLIENT3.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14472552/logCLIENT3.txt)
Standard Hay Bale (manual) load to in-game trailer (Welger DK 115) WORKS
Standard Hay Bale (manual) load to custom trailer (LSFM Güter Transportwagen / transportCart.xml) WORKS
Mod Container (catFoodPallet) (manual) load to in-game trailer (Welger DK 115) NOT WORKING
Mod Container (catFoodPallet) (manual) load to custom trailer (LSFM Güter Transportwagen / transportCart.xml) NOT WORKING

Unloading works with all combinations, also with the Mod Containers.

Here is my UniversalAutoload.xml, which is in the modSettings folder on server.
[UniversalAutoload.xml.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/14472557/UniversalAutoload.xml.txt)

**Comment by loki79uk** [comment] 2024-03-03 12:54
I've just bought another copy of FS22 so that I can reproduce this properly, waiting for it to download..  I recently built a new PC, so now can use the old one to run a test server.  I'm out again this afternoon, but will try to set it up this evening.

**Comment by FReaXit** [comment] 2024-03-03 14:32
Wow, thank you very much for your effort! Please tell me if I can help in any way.

**Comment by loki79uk** [comment] 2024-03-04 13:27
I got the game installed and dedicated server all up and running yesterday.  I'll try to make a HB savegame this evening to see if I can reproduce the issue.  You have already provided all the log files and UAL settings that I need, so thank you for that! :D

**Comment by loki79uk** [comment] 2024-03-04 22:12
> Wow, thank you very much for your effort! Please tell me if I can help in any way.

I reproduced manual loading not working for the client, BUT I can't get it to work for any objects at all.  I tried on HB and on Elmcreek, and with both maps I could not load pallets or bales as the client with either standard MP or dedi MP.  I could manually load as a player host.  Anyway, I'll see if I can get some debugging stuff going, probably later in the week, but it is defintely a bug!

**Comment by FReaXit** [comment] 2024-03-23 06:27
Hi loki, are there any news? Can i help in any way, testing?

**Comment by loki79uk** [comment] 2024-03-24 17:18
> Hi loki, are there any news? Can i help in any way, testing?

Hi, hopefully I will get some time soon!  Life seems to have got really busy lately, but past experience suggests it should all settle down eventually.. :D

**Comment by loki79uk** [comment] 2024-04-06 08:32
Sorry that it has been a whole month!  I'll get on it over the weekend.

**Comment by loki79uk** [comment] 2024-04-06 19:04
I found the reason - `g_currentMission.player.pickedUpObject` is not synced with the server in multiplayer.  I'll have to think of a workaround..

**Comment by loki79uk** [comment] 2024-04-07 12:07
> Hi loki, are there any news? Can i help in any way, testing?

I think I've finally fixed it - please try this one: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.5.1.2

**Comment by FReaXit** [comment] 2024-04-07 12:27
Thank you! 
Unfortunately i will not be able to test it before next weekend.

**Comment by loki79uk** [comment] 2024-04-07 12:31
No problem at all, just update when you can.  I will carry on testing different scenarios and game settings as well, but so far it seems fixed for me in SP and MP.

**Comment by loki79uk** [comment] 2024-05-27 09:34
> Thank you! Unfortunately i will not be able to test it before next weekend.

Have you had a chance to test this?  Is it okay to close it?

**Comment by loki79uk** [comment] 2024-06-23 17:54
Closing as fixed

**Closed by loki79uk** 2024-06-23 17:54 UTC
